/*    
 *     *    Copyright (c) 2016 Anton Bilan, Easy Bits Limited
 *      *    http://www.easy-bits.com
 *       *
 *        *    This is closed source commercial software:
 *         *    reverse-engineering, disassembly or modifications are not allowed
 *          *
 *           *    This software is distributed WITHOUT ANY WARRANTY;
 *            *    even the implied warranty of MERCHANTABILITY or FITNESS FOR 
 *             *    A PARTICULAR PURPOSE.
 *              *
 *               */
if(void 0===window)var window=self;if(void 0===window.document){var console={log:function(){for(var b=[],e=0;e<arguments.length;e++)b.push(arguments[e]);window.postMessage({t:"func",n:"log",args:b})}};window.jsv_is_ww=!0;var document={};window.navigator={appVersion:"",userAgent:""};document.URL="http://a.ca"}else window.jsv_is_ww=!1;
(function(b){function e(){}b.Qc=function(b){b.wa={};b.addEventListener=function(b,e){this.wa.hasOwnProperty(b)?this.wa[b].push(e):this.wa[b]=[e]};b.removeEventListener=function(b,e){if(this.wa.hasOwnProperty(b)){var m=this.wa[b].indexOf(e);-1!=m&&this.wa[b].splice(m,1)}};b.dispatchEvent=function(b,e){if(this.wa.hasOwnProperty(b)){var m={};m.detail=e;for(var y=this.wa[b],A=y.length,E=0;E<A;E++)y[E].apply(null,[m])}}};ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(b,e){var h=new Uint8Array(this);
void 0==e&&(e=h.length);for(var B=new ArrayBuffer(e-b),y=new Uint8Array(B),A=0;A<y.length;A++)y[A]=h[A+b];return B});e.prototype.save=function(b,e,h){var B=document.createElement("a");B.download=e;B.href="data:"+h+"/octet-stream;base64,"+b;document.body.appendChild(B);B.click()};e.prototype.ext=function(b,e){for(var h in e)"undefined"==typeof b[h]&&(b[h]=e[h]);return b};e.prototype.time=function(){return(new Date).getTime()};e.prototype.Ff=function(){var e;if(b.XMLHttpRequest)e=new b.XMLHttpRequest;
else try{e=new XDomainRequest}catch(D){try{e=new ActiveXObject("Msxml2.XMLHTTP")}catch(h){e=new ActiveXObject("Microsoft.XMLHTTP")}}return e};e.prototype.Oe=function(b,e){b.addEventListener?b.addEventListener("message",e,!1):b.attachEvent&&b.attachEvent("onmessage",e)};e.prototype.Pc=function(){return-1!=navigator.appVersion.indexOf("MSIE")||!!navigator.userAgent.match(/Trident.*rv 11\./)};e.prototype.Qa=function(b){return b.split("/")[2]};e.prototype.ic=function(b){return/[-\w]+\.(?:[-\w]+\.xn--[-\w]+|[-\w]{3,}|[-\w]+\.[-\w]{2})$/i.exec(this.Qa(b))[0]};
e.prototype.bind=function(b,e){return function(){return b.apply(e,arguments)}};e.prototype.sf=function(){return"undefined"==typeof b.postMessage?!1:!0};b.easybits_Helper=function(){return new e}})(window);
(function(b){function e(){}function m(){}function D(){this.B=[];this.$b=[];this.Fb=[];c.sf()&&c.Oe(b,c.bind(this.df,this));if(c.Pc()){var f=document.createElement("script");f.type="text/vbscript";f.text="Function easy_arr(t)\neasy_arr= CStr(t)\nEnd Function\nFunction easy_arrl(t)\neasy_arrl= ''\nif LenB(t) mod 2 Then easy_arrl= Chr(AscB(RightB(t,1)))\nEnd Function";document.body.appendChild(f)}}function h(f){this.onError=f.onError;this.bpc=f.bpc;this.mode=f.mode;this.bType=f.bType;this.Da=f.Da;this.Md=
!0;this.Lc=f.lb;this.ha=f.end;this.ff=f.Jb;this.hf=f.jb;this.Kc=f.speed;this.O=this.Vb=this.Jc=this.Nd=this.Ic=0;this.Db=this.Bb=f.start;this.Cb=[];this.F=J++}function B(){this.$e=document.URL;this.Hc=this.Xb=!1;this.Fc=!0;this.Gc;this.A;this.Ze=[]}function y(f){var e=this;A.addEventListener("error",function(f){var c;if((c=e.qf(f.detail.id))&&c.onError)c.onError(f)});K=J=0;c=b.easybits_Helper();"undefined"!=typeof f&&(F=c.ext(f,F));L=new m;t=new D;f=new B;f.Hc=!0;f=t.B.push(f)-1;t.B[f].A=f;b.Kf=function(f,
c){return t.ke(f,c)}}var A={};b.Qc(A);A.f=function(f,c){void 0===c&&(c=null);this.dispatchEvent(f,c)};var E=[],F={bpc:8E4,minbpc:.25,maxbpc:1.25},C=[],J,K,c,L,t;y.prototype.qf=function(c){for(var b=0;b<C.length;b++)if(C[b].F==c)return C[b];return!1};y.prototype.Zb=function(c){return t.Zb(c)};y.prototype.cancel=function(c){for(var b=0;b<C.length;b++)if(C[b].F==c)return C[b].Md=!1,!0;return!1};y.prototype.load=function(f){if("function"!==typeof f.Jb)throw Error("Callback is not callable");if("undefined"!==
typeof f.jb&&"function"!==typeof f.jb)throw Error("Callback is not callable");f=c.ext(f,{onError:function(){},bpc:F.bpc,mode:"range",bType:"text",wb:!1,start:0,end:"",speed:!1,Da:0});if(f.wb)for(var b=0;b<=f.lb.length;b++)E.push(f.lb[b]);f=new h(f);C.push(f);f.ef();return f.F};b.easybits_getHTTPMultiStreaming=function(c){return new y(c)};h.prototype.Ld=function(f){if(f.S==this.Db)if(this.Db+=f.J-f.S+1,this.ff({data:f.va,start:f.S,end:f.J,total:f.O,id:this.F,Of:f.Ab,Lf:this.Da&&c.ic(f.H)!=c.ic(document.URL)}),
this.Db<this.ha)for(f=0;f<this.Cb.length;f++){if(this.Cb[f].S==this.Db){this.Ld(this.Cb[f]);this.Cb.slice(f,1);break}}else this.hf({id:f.F,totaltime:(c.time()-this.Jc)/1E3,total:f.O});else this.Cb.push(f)};h.prototype.Eb=function(f){if(!(this.Bb>=this.ha&&""!=this.ha)){var b=f.bpc;if(t.B[f.A].Xb){for(var e=0,p=0,h=0;h<t.B.length;h++)f.A!=h&&t.B[h].Fc&&t.B[h].Xb&&(p++,e+=t.B[h].Xb);e&&(b=Math.round(f.bpc*t.B[f.A].Xb/(e/p)))}F.maxbpc*f.bpc<b&&(b=F.maxbpc*f.bpc);F.minbpc*f.bpc>b?t.B[f.A].Fc=!1:(e=this.Bb,
p=this.Bb+b-1,p>this.ha&&""!=this.ha&&(p=this.ha,b=p-e+1),this.Bb+=b,t.Zb({bpc:f.bpc,mode:f.mode,bType:f.bType,Pd:c.time(),S:e,J:p,H:f.H,Yb:c.bind(this.gf,this),A:f.A,F:this.F,Ab:++K,Da:this.Da}))}};h.prototype.gf=function(f){if(this.Md){this.O=f.O;if(this.ha>f.O||""==this.ha)this.ha=f.O-1;t.B[f.A].Od=t.B[f.A].Od?(t.B[f.A].Od+f.va.length/(c.time()-f.Pd))/2:f.va.length/(c.time()-f.Pd);this.Ld(f);if(!(f.J>=f.O))if(this.Kc){this.Vb+=f.va.length;var b=c.time()-this.Jc;this.Nd=1E3*this.Vb/b;if(this.Nd>
this.Kc){var e=this;setTimeout(function(){e.Eb(f)},1E3*this.Vb/this.Kc-b)}else this.Eb(f)}else this.Ic?(e=this,setTimeout(function(){e.Eb(f)},1E3*this.Ic),this.Ic=0):this.Eb(f)}else for(b=0;b<C.length;b++)if(C[b].F==this.F){C.splice(b,1);break}};h.prototype.ef=function(){this.Jc=c.time();for(var b=0;b<this.Lc.length;b++){var e=t.Wb(this.Lc[b]);if(e&&e.Fc){var x={A:e.A,H:this.Lc[b],F:this.F,bType:this.bType,mode:this.mode,bpc:this.bpc};e.Hc?this.Eb(x):t.B[e.A].Ze.push(x)}}};D.prototype.Zb=function(b){if("function"!==
typeof b.Yb)throw Error("Callback is not callable");if(-1!=E.indexOf(b.H)||c.Qa(b.H)==c.Qa(document.URL))L.Kd(b);else if(c.ic(b.H)==c.ic(document.URL)){var h=t.Wb(b.H);document.getElementById(h.Gc).contentWindow.Jf.Zb(b)}else h=t.Wb(b.H),t.Fb.push(b),document.getElementById(h.Gc).contentWindow.postMessage({source:"httpmutlistreaming",data:(new e).ee({Qd:"easy_stream_getBytes",bType:b.bType,mode:b.mode,bpc:b.bpc,S:b.S,J:b.J,H:b.H,A:b.A,F:b.F,Ab:b.Ab,Da:b.Da})},"*")};D.prototype.Wb=function(b){-1!=
E.indexOf(b)&&(b=document.URL);b=c.Qa(b);for(var e=0;e<this.B.length;e++)if(c.Qa(this.B[e].$e)==b)return this.B[e];return!1};D.prototype.ke=function(b,c){var e=this.Wb(b);e.Gc=c;e.Hc=!0;for(e=this.$b.length;e--;)if(this.$b[e].H==b){var h=this.$b[e];this.$b.splice(e,1);h.Gf(b,c,h.A)}};D.prototype.df=function(b){if(b.data.source&&"httpmutlistreaming"==!b.data.source){var h=parseInt(b.data.data.substring(0,7).replace(/^[0]+/g,"")),x=(new e).af(b.data.data.substring(7,h+7));switch(x.Qd){case "easy_onGetBytes":for(var p=
this.Fb.length;p--;)if(this.Fb[p].Ab==x.Ab){x.va=b.data.data.substring(7+h);b=this.Fb[p];this.Fb.splice(p,1);b.Da||(x.va=x.va.replace(/abcdezzz/g,String.fromCharCode(0)));b.Yb(x);break}break;case "easy_stream_getBytes":x.Yb=c.bind(this.cf,this);L.Kd(x);break;case "onLL":t.ke(x.url,x.id)}}};D.prototype.cf=function(c){var h=new e,x={},p;for(p in c)"easy_data"!=p&&(x[p]=c[p]);x.Qd="easy_onGetBytes";b.parent.postMessage({source:"httpmutlistreaming",data:h.ee(x)+c.va.replace(/\0/g,"abcdezzz")},"*")};m.prototype.We=
function(b){function e(){4==h.readyState&&b.jf(h)}var h=c.Ff();h.open("GET",b.url,!0);"text"==b.bType?c.Pc()||h.overrideMimeType("text/plain; charset=x-user-defined"):h.responseType="arraybuffer";"range"==b.mode&&h.setRequestHeader("Range","bytes="+b.S+"-"+b.J);"undefined"!=typeof h.onload?h.onload=e:h.onreadystatechange=e;h.send()};m.prototype.Kd=function(b){var e=this,h=-1==b.H.indexOf("?")?b.H+"?bytes="+b.S+b.J:b.H+"&bytes="+b.S+b.J;this.We({bpc:b.bpc,mode:b.mode,bType:b.bType,url:h,S:b.S,J:b.J,
jf:function(p){if(200>p.status||300<=p.status&&304!=p.status)return A.f("error",{id:b.F,message:"HTTP status code for "+h+" "+p.status}),!1;if(p.getResponseHeader("Content-Range"))b.O=p.getResponseHeader("Content-Range").split("/")[1];else if(b.J=b.O=p.getResponseHeader("Content-Length"),!b.O&&"range"==b.mode)return A.f("error",{id:b.F,message:"Could not stat object size "+h}),!1;b.J>b.O&&(b.J=b.O-1);if("text"==b.bType){p=c.Pc()?e.Xe(p.Nf):p.responseText;var m=p.length}else p=p.response,m=p.byteLength;
m&&(b.va=b.Hf?e.Ye(p):p,b.Yb(b))}})};m.prototype.Xe=function(b){return easy_arr(b).replace(/[\s\S]/g,function(b){b=b.charCodeAt(0);return String.fromCharCode(b&255,b>>8)})+easy_arrl(b)};m.prototype.Ye=function(b){b=b.replace(/\0/g,"abcdezzz");return"<![CDATA["+b+"]]\x3e"};e.prototype.af=function(b){var c={};b=b.split(";");for(var e=0;e<b.length;e++){var h=b[e].split("abcdefghzzz");c[h[0]]=h[1]}return c};e.prototype.ee=function(b){var c="",e;for(e in b)c+=e+"abcdefghzzz"+b[e]+";";c=c.substring(0,c.length-
1);return this.bf(c.length)+c};e.prototype.bf=function(b){var c;c=7-b.toString().length;return 0<c?Array(c+(/\./.test(b)?2:1)).join("0")+b:b+""};b.If=function(){return new e}})(window);
(function(b){function e(b){this.Na=new Uint8Array(b);this.mb=this.length=this.Na.length;this.index=0}b.ez_br=function(){return new e};e.prototype.vf=function(b){var e=this.index>>3,m=8-this.index%8;if(m>=b)return this.Na[e]>>m-b&255>>8-b;var y=(this.index+b)%8;b=this.index+b-1>>3;m=this.Na[e]&255>>8-m;for(e++;e<b;e++)m<<=8,m|=this.Na[e];return m=0<y?m<<y|this.Na[e]>>8-y:m<<8|this.Na[e]};e.prototype.c=function(b){var e=this.vf(b);this.index+=b;return e};e.prototype.advance=function(b){return this.index+=
b};e.prototype.oe=function(b){return this.index-=b};var m;b.ez_p=function(b){for(easy_processedBytes=0;easy_processedBytes+188<=b.byteLength;){m=new e(b.slice(easy_processedBytes,easy_processedBytes+188));easy_processedBytes+=188;var h;a:{if(71!=m.c(8))throw Error("Packet sync byte not found");m.c(1);m.c(1);m.c(1);m.c(13);m.c(2);h=m.c(1);m.c(1);m.c(4);if(h&&(m.c(8),m.c(1),m.c(1),m.c(1),h=m.c(1),m.c(1),m.c(1),m.c(1),m.c(1),h)){h=m.c(32);var B=m.c(16);h=((h>>31&1)+(2*h+(B>>15&1)))/9E4+(B&511)/27E6;
break a}h=!1}if(h)return h}return!1}})(window);
(function(b){function e(){this.log="";this.h=this.s=!1;this.$c=0;this.Mb=!1;this.ma=this.ud=this.Pb=null;this.kf()}function m(a,d){return function(){return a.apply(d,arguments)}}function D(){F=function(){function a(a,d,k,b){this.Cf=b;this.Zd=0;this.Gb=!1;this.xf=4096;this.sd=this.ba=this.Vc=this.ie=!1;this.ub=k;this.tb=!1;this.ua=1;this.N=this.uc=!1;this.Vd=0;this.url=a;this.hc=0;this.ec=[];this.$=[];this.WebSocket=this.node=!1;this.Ef=m(this.Ef,this);this.Sc=!1;this.gb=this.frame=0;this.Ac=Array(d);
this.Ya=d;this.Uc=m(this.Uc,this)}var d,k,c;if(d=b.AudioContext||b.webkitAudioContext){var e=navigator.userAgent.match(/Edge\/\d+/)||-1<navigator.userAgent.toLowerCase().indexOf("firefox")&&-1==navigator.userAgent.toLowerCase().indexOf("mobile");a.Pf=d&&("function"===typeof d.prototype[k="createScriptProcessor"]||"function"===typeof d.prototype[k="createJavaScriptNode"]);"function"===typeof d.prototype[c="createGainNode"]||"function"===typeof d.prototype[c="createGain"];a.prototype.connect=function(){if(!this.WebSocket&&
b.jsv_AC){this.u=b.jsv_AC;this.Jd=this.u.sampleRate;var a=this;this.WebSocket=new WebSocket(this.url);this.WebSocket.onopen=function(){a.WebSocket.binaryType="arraybuffer";a.WebSocket.onmessage=function(d){a.$.push(d.data);a.sd||(a.sd=!0,d=e?d.data.slice(0):d.data,a.u.decodeAudioData(d,function(d){a.ba=d.length/a.Jd;a.ie=1;a.Vc=a.ie*a.ba;a.uf=2<Math.floor(a.ub/a.ba)-3?Math.floor(a.ub/a.ba)-3:2},function(){}));a.Sc&&!a.hc&&a.ba&&a.$.length*a.ba>=a.ub?a.je():a.tb&&a.ba&&a.$.length*a.ba>=a.ub&&(a.tb=
!1,a.Ub(0,function(){a.play()}))}}}};a.prototype.appendBuffer=function(a,d){var k=new Uint8Array(a.byteLength+d.byteLength);k.set(new Uint8Array(a),0);k.set(new Uint8Array(d),a.byteLength);return k.buffer};a.prototype.Ub=function(a,d){var k=this;this.Cf&&0<Math.floor((a+this.$.length*this.ba-this.ub)/this.ba)-3&&this.$.shift();if(this.$.length<this.uf)this.tb=!0,this.pause();else{var b=this.$.shift(),c=b,z=this.Zd;this.Gb&&(b=this.appendBuffer(this.Gb,b));this.Gb=c;c=e?this.Gb.slice(0):this.Gb;this.u.decodeAudioData(c,
function(a){k.Zd=a.length},function(){});b=this.appendBuffer(b,this.$[0]);c=e?this.$[0].slice(0):this.$[0];this.u.decodeAudioData(c,function(a){k.u.decodeAudioData(b,function(b){for(var c=b.length-z-a.length,g=k.u.createBuffer(k.Ya,c,k.Jd),e=Array(k.Ya),H=Array(k.Ya),R=z?z-1:0,c=R+c,f=0;f<k.Ya;f++){H[f]=g.getChannelData(f);e[f]=b.getChannelData(f);for(var O=R,h=0;O<c;O++,h++)H[f][h]=e[f][O]}k.ec.push(g);d&&d()},function(){})},function(){})}};a.prototype.Uc=function(a){a=a.outputBuffer;var d,k,b,c=
a.numberOfChannels,z=Array(c);for(k=b=0;b<c;k=b+=1)z[k]=a.getChannelData(k);if(!this.frame){this.frame=this.ec.shift();this.Ub(this.Vc,!1);if(!this.frame){this.tb=!0;this.pause();return}for(k=b=this.gb=0;b<c;k=b+=1)this.Ac[k]=this.frame.getChannelData(k)}for(d=0;this.frame&&d<a.length;){k=Math.min(this.frame.length-this.gb,a.length-d);for(b=0;b<k;b+=1){for(var g=0;g<c;g++)z[g][d]=this.Ac[g][this.gb];d++;this.gb++}if(this.gb===this.frame.length){this.frame=this.ec.shift();this.Ub(this.Vc,!1);if(!this.frame){this.tb=
!0;this.pause();break}for(k=b=this.gb=0;b<c;k=b+=1)this.Ac[k]=this.frame.getChannelData(k)}}};a.prototype.je=function(){this.hc=!0;var a=this;this.Ub(0,function(){a.node=a.u[k](a.xf,a.Ya,a.Ya);a.node.onaudioprocess=a.Uc;a.ja=a.u[c]();a.ja.gain.value=a.ua;a.uc&&(a.muted=a.uc);a.node.connect(a.ja);a.ja.connect(a.u.destination)})};a.prototype.pause=function(){this.pl&&(this.Sc=!1,this.u&&(this.u.suspend?this.u.suspend():this.ja.disconnect()))};a.prototype.play=function(){this.pl||(this.Sc=!0,this.hc&&
(this.u.resume?this.u.resume():this.ja.connect(this.u.destination)),!this.hc&&this.Vd&&this.ec.length>=this.Vd&&this.je())};a.prototype.Id=function(){this.WebSocket&&this.WebSocket.close();return this.node?this.node.disconnect(0):!0};a.prototype.__defineSetter__("volume",function(a){1<arguments.length&&(a=arguments[1]);this.ua=a;this.ja&&(this.ja.gain.value=this.ua)});a.prototype.__defineSetter__("muted",function(a){1<arguments.length&&(a=arguments[1]);this.N=a;this.ja?this.ja.gain.value=this.N?0:
this.ua:this.uc=this.N});a.prototype.__defineGetter__("currentTime",function(){return this.u?this.u.currentTime:0});d=["preload","playbackRate"];for(var g=0;g<d.length;g++)a.prototype.__defineSetter__(d[g],function(){});return a}}()}function h(a){C||(C=!0,document.addEventListener?document.addEventListener("DOMContentLoaded",function k(){document.removeEventListener("DOMContentLoaded",k,!1);a()},!1):document.attachEvent&&(document.attachEvent("onreadystatechange",function k(){"complete"===document.readyState&&
(document.detachEvent("onreadystatechange",k),a())}),document.documentElement.doScroll&&b==b.top&&function z(){if(!J){try{document.documentElement.doScroll("left")}catch(b){setTimeout(z,0);return}a()}}()))}function B(){var a=document.createElement;document.createElement=function(d){return"video"==d?new b.video_jsv:a.call(document,d)};y()}function y(){var a=document.getElementsByTagName;document.getElementsByTagName=function(d){var k=a.call(document,d),k=[].slice.call(k),b=[];"video"==d&&(d=a.call(document,
"jsv"),b=[].slice.call(d));return k.concat(b)}}function A(a,d){var k=new b.video_jsv;k.style.width=a.offsetWidth+"px";k.style.height=a.offsetHeight+"px";for(var c="data-audio preload loop autoplay poster id class muted".split(" "),e=0;e<c.length;e++)a.hasAttribute(c[e])&&k.setAttribute(c[e],a.getAttribute(c[e]));k.setAttribute("src",d);a.parentNode.replaceChild(k,a)}function E(){J=!0;for(var a=document.getElementsByTagName("video"),d=0;d<a.length;d++)if("VIDEO"==a[d].tagName)if("src"in a[d]&&/\.jsv$/.test(a[d].src))A(a[d],
a[d].src);else for(var k=a[d].getElementsByTagName("source"),b=0;b<k.length;b++)/\.jsv$/.test(k[b].src)&&A(a[d],k[b].src)}(function(){for(var a=0,d=["ms","moz","webkit","o"],k=0;k<d.length&&!b.requestAnimationFrame;++k)b.requestAnimationFrame=b[d[k]+"RequestAnimationFrame"],b.cancelAnimationFrame=b[d[k]+"CancelAnimationFrame"]||b[d[k]+"CancelRequestAnimationFrame"];b.requestAnimationFrame||(b.requestAnimationFrame=function(d){var k=(new Date).getTime(),c=Math.max(0,16-(k-a)),e=b.setTimeout(function(){d(k+
c)},c);a=k+c;return e});b.cancelAnimationFrame||(b.cancelAnimationFrame=function(a){clearTimeout(a)})})();var F;b.jsv_is_ww||D();b.jsv_gl={};var C=!1,J=!1;b.jsv_gl.ial=b.jsv_gl.inu=/(iPad|iPhone|iPod|Android)/g.test(navigator.userAgent);b.jsv_gl.ios=/(iPad|iPhone|iPod)/g.test(navigator.userAgent);var K=!0;b.jsv_is_ww||("undefined"!=typeof b.jsv_config&&"undefined"!=typeof b.jsv_config.doNotPatchCreateElement&&b.jsv_config.doNotPatchCreateElement||B(),h(E));b.video_jsv=function(){function a(a,d,k){return function(){for(var b=
[],c=0;c<arguments.length;c++)b.push(arguments[c]);"set"==k&&"src"==a&&this.audioMap&&(c=d.xc(1<b.length?b[1]:b[0]),d.wc(c));d.i.postMessage({t:k,n:a,args:b})}}var d=["_goToLowerRate","play","pause","load"],k="loop src autoplay currentSrc currentTime defaultMuted defaultPlaybackRate playbackRate duration".split(" "),z="muted volume loop preload data-audio poster src autoplay buffered seeking controls currentSrc currentTime defaultMuted defaultPlaybackRate playbackRate duration ended networkState paused readyState seekable played error".split(" "),
e="muted volume loop preload data-audio poster src autoplay controls currentSrc currentTime defaultMuted defaultPlaybackRate playbackRate duration".split(" ");if(b.jsv_is_ww)var g={};else{g=document.createElement("jsv");g.style.display="block";b.Worker&&void 0!==b.jsv_config&&void 0!==b.jsv_config.worker&&(g.i=new Worker(b.jsv_config.worker),g.i.postMessage(""));var f=g.setAttribute;g.setAttribute=function(a){if(g.i&&-1!=k.indexOf(a)){for(var d=[],b=0;b<arguments.length;b++)d.push(arguments[b]);"src"==
a&&this.audioMap&&(b=g.xc(d[1]),g.wc(b));return g.i.postMessage({t:"set",n:a,args:d})}return-1!=e.indexOf(a)?(f.apply(this,arguments),c.prototype.__lookupSetter__(a).apply(this,arguments)):f.apply(this,arguments)}}for(var v in c.prototype)-1!=z.indexOf(v)?-1!=e.indexOf(v)?g.i&&-1!=k.indexOf(v)?Object.defineProperty(g,v,{configurable:!0,get:c.prototype.__lookupGetter__(v),set:a(v,g,"set")}):Object.defineProperty(g,v,{configurable:!0,get:c.prototype.__lookupGetter__(v),set:c.prototype.__lookupSetter__(v)}):
Object.defineProperty(g,v,{configurable:!0,get:c.prototype.__lookupGetter__(v)}):g[v]=g.i&&-1!=d.indexOf(v)?a(v,g,"func"):c.prototype[v];g.i&&g.i.addEventListener("message",function(a){var d=a.data;a=d.args&&!Array.isArray(d.args)?Object.keys(d.args).map(function(a){return d.args[a]}):d.args;switch(d.t){case "event":g.f(d.n,a,!0);break;case "set":g.__lookupSetter__(d.n).apply(g,a);break;case "func":"sidm"==d.n?g.vb.putImageData(a[0],0,0):g[d.n].apply(g,a);break;default:case "eq":g[d.n]=a[0];break;
case "jsv_gl":b.jsv_gl[d.n]=a[0]}});g.md();return g};var c=b.Mf=function(){this.md()};c.prototype.canPlayType=function(a){return-1!=a.indexOf("jsv")?"probably":""};c.prototype.Fe=function(){this.buffer.advance(16);this.rc.width=this.buffer.c(16);this.rc.height=this.buffer.c(16);(this.du=this.buffer.c(16)/100)||(this.du=this.buffer.c(24)/100);this.g("this","du",this.du);this.M||(this.nb=this.du*this.chunkSize/this.Ga,this.lc=Math.ceil(this.bufferSec/this.nb));!this.s&&this.Ga>W&&(this.buffer.Mb=!0);
if(452==this.buffer.c(32)){var a=this.buffer.c(32),d=this.buffer.index>>3;this.Ha={count:a,buffer:new Uint8Array(this.buffer.a.data.buffer.slice(d,d+8*a))};this.buffer.advance(8*a<<3)}};c.prototype.__defineGetter__("error",function(){return this.mc});c.prototype.__defineGetter__("readyState",function(){return this.Va});c.prototype.__defineGetter__("paused",function(){return!this.pl});c.prototype.__defineGetter__("networkState",function(){return this.sc});c.prototype.__defineGetter__("ended",function(){return this.ob});
c.prototype.__defineGetter__("preload",function(){return this.Ja});c.prototype.__defineSetter__("preload",function(a){1<arguments.length&&(a=arguments[1]);this.Ja=this.audio.le=a;this.i&&this.i.postMessage({t:"set",n:"muted",preload:[a]})});c.prototype.__defineGetter__("defaultPlaybackRate",function(){return this.hd});c.prototype.tc=function(a){a=parseFloat(a);if(0>a||1<a)a=1;return a};c.prototype.__defineSetter__("defaultPlaybackRate",function(a){1<arguments.length&&(a=arguments[1]);this.hd=this.tc(a)});
c.prototype.__defineGetter__("playbackRate",function(){return this.Qb});c.prototype.__defineSetter__("playbackRate",function(a){1<arguments.length&&(a=arguments[1]);this.Qb=this.tc(a);this.audio.playbackRate=this.Qb;this.f("ratechange")});c.prototype.__defineGetter__("defaultMuted",function(){return this.gd});c.prototype.__defineSetter__("defaultMuted",function(a){1<arguments.length&&(a=arguments[1]);this.gd=a});c.prototype.__defineGetter__("muted",function(){return this.N});c.prototype.__defineSetter__("muted",
function(a){var d=this.N;1<arguments.length&&(a=arguments[1]);this.N=a;this.audio.muted=this.N;if(this.i)this.i.postMessage({t:"set",n:"muted",args:[a]});else if(b.jsv_gl.ios||b.jsv_gl.inu)this.N||!this.mas||b.jsv_gl.ial?this.N&&this.ia&&(this.g("this","mas",!0),this.g("this","ia",!1),this.audio.pause()):(this.g("this","mas",!1),this.g("this","ia",!0),this.ws?(this.audio.connect(),this.pl&&this.audio.play()):this.yc(!0)),!a&&d&&this.g("w","inu",!1)});c.prototype.__defineGetter__("volume",function(){return this.ua});
c.prototype.__defineSetter__("volume",function(a){1<arguments.length&&(a=arguments[1]);this.ua=this.tc(a);this.audio.volume=this.ua;this.f("volumechange")});c.prototype.__defineGetter__("data-audio",function(){return this.as});c.prototype.__defineSetter__("data-audio",function(a){var d=this;1<arguments.length&&(a=arguments[1]);this.Pa=!1;this.Ma=!0;this.g("this","as",a);var k=!0;if(-1!=a.indexOf("ws://")||-1!=a.indexOf("wss://")){if(!b.AudioContext&&!b.webkitAudioContext)return this.f("error",{message:"AudioContext is not supported"}),
!1;this.g("this","at","ws");this.g("this","ws",!0);this.audio=void 0==b.jsv_au_de?new F(a,2,this.bufferMinSec+this.audioShiftSec,this.skipHard):b.jsv_au_de(a)}else-1!=a.indexOf(".m3u8")?(this.g("this","at","hls"),this.Pa=a,this.audio.Kb(""),this.audio.cc()):"."!=a.split("?")[0].substr(-4,1)?(this.g("this","at","livehttp"),this.audio.Kb(a)):(this.g("this","at","file"),k=!1,this.audio.Kb(a),this.audio.cc());""!=a?this.g("this","ia",!0):this.g("this","ia",!1);this.i&&this.i.postMessage({t:"func",n:"swaw",
args:[a]});(b.jsv_gl.ios||b.jsv_gl.inu)&&this.muted&&this.ia&&(this.g("this","mas",!0),this.g("this","ia",!1),this.audio.pause());k||this.audio.addEventListener("progress",function H(){if(!d.audio.buffered||1<d.audio.buffered.length||d.audio.buffered.length&&0<d.audio.buffered.end(d.audio.buffered.length-1))d.audio.removeEventListener("progress",H),d.Ma=!1})});c.prototype.__defineGetter__("poster",function(){return this.X?this.X.src:""});c.prototype.__defineSetter__("poster",function(a){1<arguments.length&&
(a=arguments[1]);this.X||(this.style.position="relative",this.X=document.createElement("img"),this.X.setAttribute("style","z-index:2;position:absolute;top:0px;left:0px;bottom:0px;right:0px;width:100%;height:100%;"),this.appendChild(this.X));this.X.src=a});c.prototype.__defineGetter__("played",function(){var a=this.cd(!0),d={};d.__defineGetter__("length",function(){return a.length});d.start=function(d){return a[d].start};d.end=function(d){return a[d].end};return d});c.prototype.__defineGetter__("seekable",
function(){var a=this;return{length:1,start:function(){return 0},end:function(){return a.du}}});c.prototype.__defineGetter__("buffered",function(){return this.buffer.lf()});c.prototype.__defineGetter__("seeking",function(){return this.ta});c.prototype.__defineGetter__("controls",function(){return!1});c.prototype.__defineSetter__("controls",function(){return!1});c.prototype.__defineGetter__("duration",function(){return this.du});c.prototype.__defineSetter__("duration",function(){return!1});c.prototype.__defineGetter__("src",
function(){return this.sr});c.prototype.wc=function(a){this["data-audio"]=String.prototype.replace.apply(a,this.audioMap)};c.prototype.xc=function(a){if("string"!==typeof a){this.P=a;for(var d=this.Xa=0;d<this.P.length;d++){var k=parseInt(this.P[d].b);if(this.P[d].use){this.Xa=k;a=this.P[d].src;break}this.Xa<k&&(this.Xa=k,a=this.P[d].src)}}else this.P=NaN;return a};c.prototype.__defineSetter__("src",function(a){1<arguments.length&&(a=arguments[1]);a=this.xc(a);this.zd(a)});c.prototype.__defineGetter__("currentSrc",
function(){return this.sr});c.prototype.__defineSetter__("currentSrc",function(){throw Error("Setting currentSrc is not allowed !");});c.prototype.__defineGetter__("currentTime",function(){return this.R/1E3});c.prototype.zd=function(a){this.audioMap&&!b.jsv_is_ww&&this.wc(a);this.we();this.g("this","iv",!0);this.g("this","sr",a);this.He()};c.prototype.we=function(){this.ca=!1;for(var a=0;a<this.P.length;a++)this.Xa>this.P[a].b&&(!this.ca||this.ca.b<this.P[a].b)&&(this.ca=this.P[a])};c.prototype.Ee=
function(){this.f("bitratechange",{b:this.ca.b,src:this.ca.src});this.Xa=this.ca.b;var a=this.R/1E3,d=this;this.addEventListener("loadedmetadata",function z(){d.removeEventListener("loadedmetadata",z);d.addEventListener("seeked",function g(){d.removeEventListener("seeked",g);d.play()});d.currentTime=a});this.zd(this.ca.src)};c.prototype.cd=function(a){return a?JSON.parse(JSON.stringify(this.xd)):this.xd};c.prototype.f=function(a,d,k){void 0===d&&(d=null);if(b.jsv_is_ww)this.dispatchEvent(a,d),void 0==
k&&b.postMessage({t:"event",n:a,args:d});else{var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!1,!1,d);this.dispatchEvent(c);this.i&&void 0==k&&this.i.postMessage({t:"event",n:a,args:d})}};c.prototype.Ie=function(a){if(this.Ha){try{this.xa(G)}catch(k){this.C(k);return}this.$a();this.xa(M);this.Tb()}else{a*=1E3;this.xa(G);this.$a();this.xa(M);this.Tb();try{for(;a-this.R>X;)this.xa(G),this.$a(),this.xa(M),this.Tb()}catch(k){this.C(k);return}}if(this.ia)if(this.Ma){var d=this;this.audio.addEventListener("timeupdate",
function z(){d.audio.removeEventListener("timeupdate",z);d.Ma=!1;d.pl||d.audio.pause();d.yc()});this.audio.play()}else this.yc();else this.td()};c.prototype.yc=function(a){var d=this,k=4;this.audio.addEventListener("seeked",function H(){k--;if(2<Math.abs(d.currentTime-d.Sa-d.audio.currentTime))return k&&d.audio.Dc(d.currentTime-d.Sa),!1;d.audio.removeEventListener("seeked",H);d.pl&&d.audio.play();void 0===a&&d.td()});this.audio.Dc(this.currentTime-this.Sa)};c.prototype.oc=function(a){var d=this.Ha.buffer;
a=8*a+4;return 60*(60*((d[a]&124)>>2)+(((d[a]&3)<<4)+((d[a+1]&240)>>4)))+(((d[a+1]&7)<<3)+((d[a+2]&224)>>5))+(((d[a+2]&31)<<1)+((d[a+3]&128)>>7)+1)/this.kb};c.prototype.ye=function(a){var d=Math.floor(this.Ha.count*a/this.du),k=this.oc(d);if(k>a)for(;k>a&&0<d;)d--,k=this.oc(d);else if(k<a){for(;k<=a&&d<this.Ha.count;)d++,k=this.oc(d);k>a&&d--}d*=8;a=this.Ha.buffer;return(a[d]<<24)+(a[d+1]<<16)+(a[d+2]<<8)+a[d+3]};c.prototype.td=function(){this.ta=!1;this.bspl&&this.Ta&&this.play();this.vc=NaN;this.f("seeked");
this.pl&&(this.f("canplay"),this.f("playing"),this.f("canplaythrough"));this.f("timeupdate")};c.prototype.__defineSetter__("currentTime",function(a,d){if(this.s)return!1;if(this.ia&&b.jsv_gl.ial)if(this.N)this.g("this","mas",this.as),this.g("this","ia",!1);else return!1;if(a>this.du)return this.ra("Time out of range");void 0===d&&this.g("this","bspl",this.pl);b.cancelAnimationFrame(this.sa);b.clearTimeout(this.Ka);this.Le(a,d)});c.prototype.Le=function(a,d){void 0===d&&this.pause();this.cd(!1);this.La=
this.Y=this.ob=!1;this.ta=!0;this.vc=a;if(this.rc.width){var k=this.Ha?this.ye(a):Math.round(this.Ga*a/this.du);try{this.buffer.seek(k)&&this.Ie(a)}catch(b){this.C(b)}}else this.Rb("v"),this.C(void 0,void 0,!1)};c.prototype.__defineGetter__("loop",function(){return this.rd});c.prototype.__defineSetter__("loop",function(a){this.rd=a});c.prototype.__defineGetter__("autoplay",function(){return this.dd});c.prototype.__defineSetter__("autoplay",function(a){this.dd=a});c.prototype.nd=function(a){if(this.pl&&
this.Yd&&this.Yd==this.audio.currentTime){if(2<++this.Rc)return this.Rc=0,!1}else this.Rc=0;this.Yd=this.audio.currentTime;if(!this.audio.buffered.length)return!0;for(var d=this.audio.currentTime,b=0;b<this.audio.buffered.length;b++)if(this.audio.buffered.end(b)>d&&this.audio.buffered.start(b)<=d){if(this.audio.buffered.end(b)-d>=a)return!0;break}return!1};c.prototype.Ge=function(){if(!this.La){this.Rb("a");var a=this,d=function(){a.nd(a.bufferMinSec)&&(a.audio.removeEventListener("progress",d),a.Nb("a"))};
this.audio.addEventListener("progress",d,!1)}};c.prototype.se=function(){if(K){K=!1;var a=b.AudioContext||b.webkitAudioContext;if(a){var a=new a,d=a.createBuffer(1,1,22050),k=a.createBufferSource();k.buffer=d;k.connect(a.destination);k["function"==typeof k.noteOn?"noteOn":"start"](0);b.jsv_AC=a}}};c.prototype.Df=function(){function a(a){v=Date.now();d=a.touches[0].pageX;k=a.touches[0].pageY}var d,k,c=this,e=b.location!=top.location&&this.Mc.Qa(document.referrer)==this.Mc.Qa(document.URL),g=0;if(b.jsv_gl.ios)var f=
navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/),g=parseInt(f[1],10)+parseInt(f[2],10)/10;var v,l="touchstart";9<=g&&9.2>g&&(document.documentElement.addEventListener("touchstart",a,!1),e&&b.parent.addEventListener("touchstart",a,!1),l="touchend");f=function S(f){if(9<=g&&9.2>g)if(f=Math.sqrt(Math.pow(f.changedTouches[0].pageX-d,2)+Math.pow(f.changedTouches[0].pageY-k,2)),100>Date.now()-v&&10>f)document.documentElement.removeEventListener("touchstart",a),e&&b.parent.removeEventListener("touchstart",
a);else return;document.documentElement.removeEventListener(l,S);e&&b.parent.removeEventListener(l,S);c.unlockaudio()};document.documentElement.addEventListener(l,f,!1);e&&b.parent.addEventListener(l,f,!1)};c.prototype.unlockaudio=function(){this.audio.play();this.audio.pause();this.se();this.g("w","ial",!1);this.f("audiounlocked")};c.prototype.Nb=function(a,d){this.f("unstalled");if("v"==a){var b=this.ws?this.bufferMinSec+1:this.De();if(this.ta||b>=this.bufferMinSec||d==this.Ga)this.Y=!1,this.La||
(this.Va=4,this.g("this","pl",this.wpl),this.wpl&&this.ia&&(this.ws||this.audio.play())),this.ta?this.__lookupSetter__("currentTime").apply(this,[this.vc,!0]):this.wpl&&(this.ws||(this.sb=!0),this.Ba(),this.pl&&this.f("playing"))}else if(this.La=!1,!this.Y){var c=this;this.audio.addEventListener("play",function g(){c.audio.removeEventListener("play",g);c.Va=4;c.pl=c.wpl;c.Ba();c.pl&&c.f("playing")});this.audio.play()}};c.prototype.Rb=function(a){this.Y||this.La||(this.g("this","wpl",this.pl),this.g("this",
"pl",!1),this.f("stalled"),this.Va=1,this.ws||this.audio.pause());"v"==a?this.Y||(b.cancelAnimationFrame(this.sa),b.clearTimeout(this.Ka),this.Lb=!1,this.Y=!0,this.ws&&(this.Sb=0)):this.La=!0};c.prototype.log=function(){console.log.apply(console,arguments)};c.prototype.ma=function(a){this.Rb("v");if(!this.ws)throw a;};c.prototype.bind=function(a,d){return function(){return a.apply(d,arguments)}};c.prototype.wd=function(){this.Ob=this.Rc=0;this.yd=[];this.Wc=!1;this.WebSocket&&(this.WebSocket.close(),
this.WebSocket=!1);b.clearInterval(this.kc);b.clearTimeout(this.Ka);b.clearInterval(this.qc);b.cancelAnimationFrame(this.sa);this.Ad=0;this.sb=!1;this.Bd=!0;this.Wa=this.Sb=0;this.mc={code:0,message:""};this.Ia={start:-2,end:-1,W:""};this.Ha=!1;this.ld=0;this.pc=!1;this.Sa=this.nb=0;this.h=[];this.pb=!1;this.s=-1;this.M=!1;this.g("this","ws",!1);this.lc=x;this.nc=!0;this.xd=[];this.sc=this.Va=0;this.ob=!1;this.G=this.v=NaN;this.g("this","pl",!1);this.g("this","wpl",!1);this.g("this","bspl",!1);this.Y=
this.La=!1;this.qa&&(this.Ua.cancel(this.rb),this.f("suspend"));this.qa=!1;this.vc=this.rb=NaN;this.ta=!1;this.rc={};this.Fa=!1;this.Ga=NaN;this.Ea=0;this.du=this.ed=NaN;this.buffer=new e;this.buffer.ma=this.bind(this.ma,this);this.buffer.ud=this.bind(this.C,this);this.buffer.Pb=this.bind(this.Pb,this);this.R=0};c.prototype.He=function(){b.clearInterval(this.kc);b.clearTimeout(this.Ka);b.clearInterval(this.qc);b.cancelAnimationFrame(this.sa);var a=this;this.Lb?b.setTimeout(function(){a.vd()},1E3/
a.fc):this.vd()};c.prototype.vd=function(){this.wd();var a=this.sr.split(".").pop();if("jsv"==a)this.s=this.buffer.s=!1,this.W=this.sr;else if("m3u8"==a)this.M=!0,this.W=NaN;else if(0==this.sr.indexOf("ws://")||0==this.sr.indexOf("wss://")){if(this.g("this","ws",!0),this.s=this.buffer.s=!0,this.buffer.Mb=!0,!b.WebSocket){this.ra("WebSockets are not supported");return}}else{this.ra("Unsupported src");return}this.M?this.kd():this.ws||("auto"==this.Ja?this.C(0):"metadata"==this.Ja&&this.be(0,this.chunkSize,
!1));this.f("srcchange");this.ws&&this.autoplay&&this.play()};c.prototype.xe=function(){for(var a=this.buffer.a,d=0,b=0,c=!1;a;){d++;0==a.data[0]&&0==a.data[1]&&1==a.data[2]&&a.data[3]==G&&(c=a.start,this.Ad==c&&(c=!1));c&&b++;if(b>this.Wa&&3<d-b&&1<d){this.Ad=c;this.sb=!0;return}a=a.next}d<this.Wa-3?this.pl&&(this.te=!0,this.g("this","pl",!1)):this.te&&(this.te=!1,this.g("this","pl",!0),this.Ba())};c.prototype.Me=function(){var a=this,d=new ArrayBuffer(0),b=0;this.WebSocket=new WebSocket(this.sr);
this.WebSocket.onopen=function(){a.WebSocket.binaryType="arraybuffer";a.WebSocket.onmessage=function(c){if(a.Bd){var e=new Uint8Array(c.data);if(0!=e[0]||0!=e[1]||1!=e[2]||e[3]!=G)return;a.Bd=!1}a.Sb++;d=c.data;c=b+d.byteLength-1;a.Ea+=d.byteLength;a.pb=!0;a.buffer.Dd({data:d,total:d.byteLength,start:b,l:b,end:c,m:c});b=c+1;if(!(a.Sb<a.Wa)){a.skipHard&&a.xe();if(a.Y)try{a.Nb("v",-1)}catch(g){return!1}if(!a.Fa){if(!a.Wa)try{a.xa(G),a.Rd=a.buffer.index,a.$a()}catch(g){return a.buffer.index=a.buffer.j=
0,!1}if(a.Sb<a.Wa)return;a.Ta&&(a.Ba(),a.pl&&a.f("playing"));a.f("durationchange");a.f("resize");a.f("loadedmetadata");a.f("loadeddata")}a.f("progress");a.Fa||(a.Fa=!0,a.f("canplay"),a.f("canplaythrough"),a.play());a.Va=4}}}};c.prototype.Pb=function(a){this.Ea-=a.data.byteLength;if(this.M&&(this.jd(a.start).loaded=!1,this.s))for(;this.h[0].start<=a.start;)this.h.splice(0,1)};c.prototype.Be=function(){for(var a=this.audio.currentTime+this.Sa,d=0;d<this.h.length;d++)if(this.h[d].l>=a)return this.h[d].start;
return 0};c.prototype.ze=function(a){var d="",k=this;this.Ua.load({start:0,end:1E3,bType:"arraybuffer",wb:!0,lb:[a],onError:function(a){k.ra(a.detail.message)},Jb:function(a){d=a.data},jb:function(){var a=b.ez_p(d);k.Sa=a-.7;k.C(k.Be());k.pb=!0;k.play()}})};c.prototype.Ce=function(){var a,d=this;this.Ua.load({mode:"whole",bType:"text",wb:!0,lb:[this.audio.src],onError:function(a){d.ra(a.detail.message)},Jb:function(d){a=d.data},jb:function(){d.Je(a)}})};c.prototype.Je=function(a){a=a.match(/.*\.ts/g)[0];
if(0!=a.indexOf("http")){var d=this.audio.src.split("/");d.pop();d=d.join("/")+"/";a=d+a}this.ze(a)};c.prototype.Ke=function(a){a=a.split(/\n/g);a.pop();var d=0,b=this.sr.split("/");b.pop();for(var b=b.join("/")+"/",c=this.h.length?this.h[this.h.length-1].end+1:0,e=[],g=0;g<a.length;g++){var f=a[g].split(","),v=parseFloat(f[3]),l=0!=f[0].indexOf("http")?b+f[0]:f[0];e.push(l);-1==this.yd.indexOf(l)&&(d++,this.h.push({loaded:!1,start:c,end:c+v-1,byteLength:v,url:l,l:parseFloat(f[1]),m:parseFloat(f[2])}),
c+=v)}this.yd=e;this.ld=a.length;this.f("vls");-1==this.s&&(this.nb=this.h[0].m-this.h[0].l,this.lc=Math.ceil(this.bufferSec/this.nb),this.buffer.h=this.h,1<this.h[0].l?(this.s=this.buffer.s=!0,this.buffer.Mb=!0,this.qc=setInterval(this.kd.bind(this),1E3*this.nb)):(this.s=this.buffer.s=!1,"auto"==this.Ja?this.C(0):"metadata"==this.Ja&&this.C(0,!0,!1)));d&&this.pb&&this.C(void 0,!0)};c.prototype.kd=function(){var a,d=this;this.Ua.load({mode:"whole",bType:"text",wb:!0,lb:[this.sr],onError:function(a){d.ra(a.detail.message)},
Jb:function(d){a=d.data},jb:function(){d.Ke(a)}})};c.prototype.Ae=function(a){for(var d=this.h.length-1;0<=d;d--)if(this.h[d].url==a)return this.h[d];return!1};c.prototype.jd=function(a){for(var d=0;d<this.h.length;d++)if(this.h[d].start==a)return this.h[d];return!1};c.prototype.fd=function(){clearTimeout(this.od)};c.prototype.ve=function(){if(!this.ws){var a=this,d=function(){a.pd=Date.now();a.od=setTimeout(d,50)};d();var b=function(){a.pl&&700<Date.now()-a.pd&&a.pause(!0)};this.audio.removeEventListener("timeupdate",
b);this.audio.addEventListener("timeupdate",b,!1)}};c.prototype.destroy=function(){this.reset();delete this.audio;this.parentNode.removeChild(this);this.i&&this.i.terminate()};c.prototype.reset=function(){this.ia&&(this.audio.Id?this.audio.Id():this.audio.load&&(this.audio.src="",this.audio.load()));this.at="file";this.Xa=0;this.P=NaN;this.g("this","sr",NaN);this.W=NaN;this.as="";this.od=this.pd=this.mas=this.Pa=this.iv=this.ia=!1;this.Qb=this.hd=this.ua=1;this.N=this.gd=!1;this.Ja="auto";this.rd=
this.dd=this.X=!1;this.wd();this.i&&this.i.postMessage({t:"func",n:"reset",args:[]})};c.prototype.ra=function(a){this.f("error",{message:a});this.mc.message=a;return!1};c.prototype.md=function(){var a=this;this.ca=this.Lb=!1;this.Ta=this.Ma=!0;this.WebSocket=this.sa=this.Ka=this.kc=this.qc=!1;this.reset();var d={unlockAudio:!0,syncInt:5E3,audioMap:!1,audioShiftSec:t,nogl:!1,skipHard:!1,bufferSec:V,chunkSize:p,bufferMinSec:f};this.Mc=b.easybits_Helper();"undefined"!=typeof b.jsv_config&&(d=this.Mc.ext(b.jsv_config,
d));for(var k in d)d.hasOwnProperty(k)&&(this[k]=d[k]);!b.jsv_is_ww&&this.unlockAudio&&(b.jsv_gl.ial?this.Df():this.se());if(this.bufferMinSec>=this.bufferSec)this.ra("bufferMinSec must be smaller bufferSec");else{this.Ua=b.easybits_getHTTPMultiStreaming({bpc:this.chunkSize});this.re;this.Ed=new Uint8Array(64);this.Fd=new Uint8Array(64);this.D=new Int32Array(64);if(b.jsv_is_ww){this.audio=new function(){this.le="auto";this.src="";this.zc=this.currentTime=0;var a=this;this.buffered={length:1,start:function(){return 0},
end:function(){return a.zc?a.zc:9999999}}};b.Qc(this);b.Qc(this.audio);k=function(a,d){return function(){for(var k=[],c=0;c<arguments.length;c++)k.push(arguments[c]);b.postMessage({t:"func",n:a,args:[d,k]})}};for(var c=["play","pause","connect"],e=["playbackRate","muted","volume"],d=0;d<c.length;d++)this.audio[c[d]]=k("afun",c[d]);this.audio.Dc=k("aset","currentTime");this.audio.Kb=k("aset","src");this.audio.cc=k("afun","load");for(d=0;d<e.length;d++)Object.defineProperty(this.audio,e[d],{set:k("aset",
e[d])})}else if(this.canvas=document.createElement("canvas"),this.canvas.style.width="100%",this.canvas.style.height="100%",this.appendChild(this.canvas),this.audio=document.createElement("audio"),this.audio.Dc=function(d){a.audio.currentTime=d},this.audio.Kb=function(d){a.audio.src=d},this.audio.cc=function(){a.audio.load()},this.i){this.g("w","ial",b.jsv_gl.ial);this.g("w","ios",b.jsv_gl.ios);for(k in d)d.hasOwnProperty(k)&&this.i.postMessage({t:"eq",n:k,args:[d[k]]});k=["progress","seeked","play",
"timeupdate","stalled"];c=function(d){return function(){a.i.postMessage({t:"func",n:"ae",args:[d]})}};for(d=0;d<k.length;d++)this.audio.addEventListener(k[d],c(k[d]));this.audio.addEventListener("timeupdate",function(){var d=a.audio.buffered&&a.audio.buffered.length?a.audio.buffered.end(a.audio.buffered.length-1):0;a.i.postMessage({t:"func",n:"aet",args:[a.audio.currentTime,d]})});this.audio.addEventListener("progress",function(){var d=a.audio.buffered&&a.audio.buffered.length?a.audio.buffered.end(a.audio.buffered.length-
1):0;a.i.postMessage({t:"func",n:"aet",args:[a.audio.currentTime,d]})})}b.jsv_is_ww||(!this.nogl&&this.Wd()?this.gc=this.ne:(this.vb=this.canvas.getContext("2d"),this.gc=this.zf),this.i&&this.i.postMessage({t:"func",n:"srfw",args:[this.U?"gl":"2d"]}),this.addEventListener("play",function(){a.X&&"none"!=a.X.style.display&&(a.X.style.display="none")}));this.audio.le=this.Ja}};c.prototype.be=function(a,d,b){"undefined"==typeof b&&(b=!0);if(this.M)c=a,e=d,a=0,d="";else{"undefined"==typeof a?(a=0,d=""):
a%this.chunkSize&&(a=Math.floor(a/this.chunkSize)*this.chunkSize);d=Math.ceil(d/this.chunkSize)*this.chunkSize-1;var c=a,e=d}if(!this.qa||this.Ia.start!=c||this.W!=this.Ia.W){this.qa&&(this.Ua.cancel(this.rb),this.f("suspend"));this.sc=2;this.qa=!0;this.Ia={start:c,end:e,W:this.W};var g=this,f=this.W;a={mode:this.M?"whole":"range",bType:"arraybuffer",start:a,end:d,wb:!0,lb:[this.W],onError:function(a){g.ra(a.detail.message)},Jb:function(a){if(a.id!=g.rb)return!1;a.url=f;g.wf(a)},jb:function(a){if(a.id!=
g.rb)return!1;g.sc=1;g.qa=!1;b&&g.C(g.Ia.end+1)}};this.Fa||this.f("loadstart");this.rb=this.Ua.load(a)}};c.prototype.nf=function(a){a=this.jd(a);if(!a)return!1;var d=this.buffer.a?this.buffer.a.m:0;return a&&(this.s||this.ta||a.l-d<=this.bufferSec)?(this.W=a.url,{start:a.start,end:a.end}):!1};c.prototype.C=function(a,d,b){if(0!==a%1&&void 0!==a)throw Error("not int");if(this.ws)return!1;void 0==b&&(b=!0);if("undefined"!=typeof d&&this.qa)return!1;this.M?("undefined"==typeof a&&(a=this.Ia.end+1),a=
this.nf(a)):("undefined"==typeof a&&(a=Math.floor(this.buffer.index>>3)),a=this.buffer.mf(a,this.chunkSize,this.lc,this.ta));a&&this.be(a.start,a.end,b)};c.prototype.De=function(){if(!this.buffer.o)return 0;var a=this.buffer.a,d=0,b=0;if(this.buffer.o.start!=a.start||a.next)for(;a.next&&a.end+1==a.next.start;)this.M?b+=a.m-a.l:d+=a.data.byteLength,a=a.next;else this.M?b=this.buffer.o.m-this.buffer.o.l:d=a.data.byteLength;!this.M&&d&&(b=this.du*d/this.Ga);return b};c.prototype.wf=function(a){var d=
a.data.byteLength;this.Ia.start+=d;this.Ea+=d;this.M?(d=this.Ae(a.url),d.loaded=!0,a.start=d.start,a.end=d.end,a.l=d.l,a.m=d.m):(this.Ga=a.total,a.l=this.du*a.start/a.total,a.m=this.du*a.end/a.total);this.buffer.Dd(a);this.Ga==this.Ea&&(this.buffer.qd=!0,this.f("loaded"));if(this.Fa)this.Y&&this.Nb("v",a.end+1);else{this.Fe();this.Y&&this.Nb("v",a.end+1);this.buffer.w.l=this.du*a.start/a.total;this.buffer.w.m=this.du*a.end/a.total;this.f("durationchange");this.f("resize");this.f("loadedmetadata");
this.f("loadeddata");this.Fa=!0;this.f("canplay");try{this.xa(G),this.Rd=this.buffer.index,this.$a(),this.Ta&&(this.Ba(),this.pl&&this.f("playing"))}catch(b){this.C(b,!0);return}this.f("canplaythrough");this.autoplay&&this.play()}this.f("suspend");this.f("progress");this.Va=4};c.prototype.g=function(a,d,k){"this"==a?(this[d]=k,a="eq"):(b.jsv_gl[d]=k,a="jsv_gl");this.i?this.i.postMessage({t:a,n:d,args:[k]}):b.jsv_is_ww&&b.postMessage({t:a,n:d,args:[k]})};c.prototype.swaw=function(a){this.Pa=!1;this.audio.src=
a;-1!=a.indexOf(".m3u8")&&(this.Pa=a)};c.prototype.aset=function(a,d){this.audio[a]=d[0]};c.prototype.aet=function(a,d){this.audio.currentTime=a;this.audio.zc=d};c.prototype.ae=function(a){this.audio.dispatchEvent(a,null)};c.prototype.afun=function(a,d){this.audio[a].apply(this.audio,d)};c.prototype.load=function(){this.f("abort");this.f("emptied");this.qa||this.C()};c.prototype.play=function(){var a=this;if(""!=this.mc.message)return!1;if(!this.pl){if(this.ia&&b.jsv_gl.ial)if(this.N)this.g("this",
"mas",this.as),this.g("this","ia",!1);else return!1;if(this.Y||this.La)return!1;if(this.nc){this.nc=!1;if(this.s&&this.M&&!this.ia){if(!this.h.length)return a=this,this.addEventListener("vls",function z(){a.removeEventListener("vls",z);a.play()}),this.nc=!0,!1;this.C(this.h[this.h.length-this.ld].start);this.pb=!0}this.Pa&&(this.audio.Kb(this.Pa),this.Pa=!1);var d=!1;this.ia&&this.Ma&&("ws"!=this.at?(this.audio.addEventListener("timeupdate",function z(){a.Ma=!1;a.audio.removeEventListener("timeupdate",
z);a.audio.pause();a.s&&"hls"==a.at&&a.Ce();a.play()}),this.audio.play(),d=!0):(this.Ma=!1,this.audio.connect()));this.ws&&this.iv&&(this.Me(),d=!0);if(d)return}else if(this.s&&!this.pb)return;!this.ia||b.jsv_is_ww||this.i||this.ve();this.g("this","pl",!0);this.g("this","wpl",!0);setTimeout(function(){a.f("play")},50);this.Fa&&setTimeout(function(){a.f("playing")},51);this.qa||this.C();this.Ca=Date.now();this.ia&&("livehttp"==this.at&&this.audio.cc(),this.audio.play());if(this.ob)return this.ob=!1,
this.currentTime=0,!0;if(!this.buffer.a)return this.Rb("v"),!1;this.pe()}};c.prototype.pause=function(){if(!this.pl)return!1;b.cancelAnimationFrame(this.sa);b.clearTimeout(this.Ka);b.clearInterval(this.kc);this.g("this","pl",!1);this.g("this","wpl",!1);this.ia&&this.audio.pause();!this.ia||b.jsv_is_ww||this.i||this.fd();this.f("pause")};c.prototype.aa=function(a){var d=0;do d=a[d+this.buffer.c(1)];while(0<=d&&0!=a[d]);return a[d+2]};c.prototype.xa=function(a){for(var d;d=this.buffer.bc(),d!=a&&d!=
e.jc&&d!=e.pa;);};c.prototype.ac=function(a,d){for(var b=0,c=a.length;b<c;b++)a[b]=d};c.prototype.kb=30;c.prototype.fc=30;c.prototype.$d=0;c.prototype.Rd=0;c.prototype.Ca=0;c.prototype.Ba=function(){try{if(b.cancelAnimationFrame(this.sa),b.clearTimeout(this.Ka),this.Lb=!0,this.buffer){for(;;){var a=this.buffer.bc();if(a==G)this.sb&&(this.Ca=Date.now()+1E3/this.fc,this.sb=!1),this.$a();else if(!this.sb)if(a==M)this.Tb();else{if(a==Y)return this.pl&&!this.ta&&this.pe(),this.Ue(),this.canvas;if(a==e.jc)return this.g("this",
"pl",!1),this.ob=!0,this.ia&&this.audio.pause(),!this.ia||b.jsv_is_ww||this.i||this.fd(),this.f("pause"),this.f("ended"),this.loop&&this.Wc&&this.play(),null;if(a==e.pa)break}}this.Lb=!1}}catch(d){this.C(d)}};c.prototype.pe=function(){this.$d=Date.now()-this.Ca;var a=Math.max(0,1E3/this.kb-this.$d);this.Ca=Date.now()+a;this.R+=1E3/this.kb;if(this.ia&&!this.ws){var d=this.R-1E3*(this.audio.currentTime+this.Sa);if(300>d)if(-100<d)a-=100,this.Ca-=100;else{if(this.pc){this.Ob++;this.Ob>L&&this.ca&&this.Ee();
this.audio.pause();var k=this;b.clearTimeout(this.re);this.re=setTimeout(function(){k.pl&&k.audio.play()},400-d)}}else if(500<d){if(this.Ob=0,this.pc){if(!this.s&&!this.nd(.2))if(this.audio.paused)this.audio.play();else{this.Ge();return}a+=100;this.Ca+=100}}else this.Ob=0}18>a?this.sa=b.requestAnimationFrame(this.bind(this.Ba,this),this.canvas):(k=this,this.Ka=b.setTimeout(function(){k.sa=b.requestAnimationFrame(k.bind(k.Ba,k),k.canvas)},a))};c.prototype.Tb=function(){this.pc=!0;this.buffer.advance(1);
var a=this.buffer.c(5),d=this.buffer.c(6);this.buffer.advance(1);var b=this.buffer.c(6),c=this.buffer.c(6);this.R=1E3*(60*(60*a+d)+b+(c+1)/this.kb)};c.prototype.$a=function(){this.v=this.buffer.c(12);this.G=this.buffer.c(12);this.buffer.advance(4);this.kb=Z[this.buffer.c(4)];this.fc=this.kb*this.Qb;this.Wa=Math.ceil(this.fc*this.bufferMinSec);if(this.ed)a=30;else{this.ed=this.buffer.c(18);var a=12}this.buffer.advance(a);this.rf();if(this.buffer.c(1)){for(a=0;64>a;a++)this.Ed[P[a]]=this.buffer.c(8);
this.Xd=this.Ed}if(this.buffer.c(1)){for(a=0;64>a;a++)this.Fd[P[a]]=this.buffer.c(8);this.he=this.Fd}};c.prototype.me=function(a,d){this.canvas.parentNode.removeChild(this.canvas);this.canvas=document.createElement("canvas");this.canvas.width=a;this.canvas.height=d;this.canvas.style.width="100%";this.canvas.style.height="100%";this.Wd();this.appendChild(this.canvas);this.f("canvas")};c.prototype.rf=function(){this.Xd=aa;this.he=ba;this.Aa=this.v+15>>4;this.de=this.G+15>>4;this.tf=this.Aa*this.de;
this.I=this.Aa<<4;this.Pe=this.de<<4;this.Za=this.I*this.Pe;this.hb=this.Aa<<3;if(!this.Wc){this.Wc=!0;b.jsv_is_ww&&b.postMessage({t:"func",n:"swhm",args:[this.v,this.G,this.I,this.hb]});var a=b.Uint8ClampedArray||b.Uint8Array;b.Uint8ClampedArray||(this.Gd=this.Qe,this.Cd=this.Ne);this.ga=new a(this.Za);this.Ec=new Uint32Array(this.ga.buffer);this.ea=new a(this.Za>>2);this.Cc=new Uint32Array(this.ea.buffer);this.da=new a(this.Za>>2);this.Bc=new Uint32Array(this.da.buffer);this.fb=new a(this.Za);this.Ud=
new Uint32Array(this.fb.buffer);this.cb=new a(this.Za>>2);this.Td=new Uint32Array(this.cb.buffer);this.bb=new a(this.Za>>2);this.Sd=new Uint32Array(this.bb.buffer);b.jsv_is_ww||(this.canvas.width=this.v,this.canvas.height=this.G,this.U?(b.jsv_gl.ios&&this.me(this.v,this.G),this.U.useProgram(this.V),this.U.viewport(0,0,this.v,this.G)):(this.fa=this.vb.getImageData(0,0,this.v,this.G),this.ac(this.fa.data,255)))}};c.prototype.ga=null;c.prototype.ea=null;c.prototype.da=null;c.prototype.fa=null;c.prototype.na=
0;c.prototype.fb=null;c.prototype.cb=null;c.prototype.bb=null;c.prototype.Oc=!1;c.prototype.Nc=0;c.prototype.eb=0;c.prototype.T=0;c.prototype.Ue=function(){this.buffer.advance(10);this.na=this.buffer.c(3);this.buffer.advance(16);if(!(0>=this.na||this.na>=ca)){if(this.na==N){this.Oc=this.buffer.c(1);this.Nc=this.buffer.c(3);if(0==this.Nc)return;this.eb=this.Nc-1;this.T=1<<this.eb}var a;do a=this.buffer.bc();while(a==da||a==ea);for(;a>=fa&&a<=ga;)this.Ve(a&255),a=this.buffer.bc();this.buffer.oe(32);
void 0!=ha&&this.gc();if(this.na==ia||this.na==N){a=this.fb;var d=this.Ud,b=this.cb,c=this.Td,e=this.bb,g=this.Sd;this.fb=this.ga;this.Ud=this.Ec;this.cb=this.ea;this.Td=this.Cc;this.bb=this.da;this.Sd=this.Bc;this.ga=a;this.Ec=d;this.ea=b;this.Cc=c;this.da=e;this.Bc=g}}};c.prototype.ad=function(){for(var a=this.ga,d=this.da,b=this.ea,c=this.fa.data,e=0,g=this.I,f=this.I+(this.I-this.v),v=0,l=this.hb-(this.v>>1),h=0,m=4*this.v,n=4*this.v,q=this.v>>1,p=this.G>>1,r,u,w,t,x=0;x<p;x++){for(var y=0;y<
q;y++)r=d[v],u=b[v],v++,w=u+(103*u>>8)-179,u=(88*r>>8)-44+(183*u>>8)-91,t=r+(198*r>>8)-227,r=a[e++],c[h]=r+w,c[h+1]=r-u,c[h+2]=r+t,h+=4,r=a[e++],c[h]=r+w,c[h+1]=r-u,c[h+2]=r+t,h+=4,r=a[g++],c[m]=r+w,c[m+1]=r-u,c[m+2]=r+t,m+=4,r=a[g++],c[m]=r+w,c[m+1]=r-u,c[m+2]=r+t,m+=4;e+=f;g+=f;h+=n;m+=n;v+=l}};c.prototype.sidmgl=function(a,d,b,c){this.ga=a;this.ea=d;this.da=b;this.ne();this.R=c};c.prototype.sidm2d=function(a,d){this.vb.putImageData(a,0,0);this.R=d;var b=document.createEvent("CustomEvent");b.initCustomEvent("timeupdate",
!1,!1,null);this.dispatchEvent(b)};c.prototype.sidw=function(a){this.fa=a;this.Ta||(this.Ba(),this.pl&&this.f("playing"));this.Ta=!0};c.prototype.swhm=function(a,d,c,e){this.v=a;this.G=d;this.I=c;this.hb=e;this.canvas.width=this.v;this.canvas.height=this.G;this.U?(b.jsv_gl.ios&&this.me(this.v,this.G),this.U.useProgram(this.V),this.U.viewport(0,0,this.v,d)):(this.fa=this.vb.getImageData(0,0,this.v,this.G),this.ac(this.fa.data,255),this.i.postMessage({t:"func",n:"sidw",args:[this.fa]}))};c.prototype.srfw=
function(a){"2d"==a?(this.gc=this.Af,this.Ta=!1):this.gc=this.Bf};c.prototype.Af=function(){this.ad();b.postMessage({t:"func",n:"sidm2d",args:[this.fa,this.R]})};c.prototype.Bf=function(){b.postMessage({t:"func",n:"sidmgl",args:[this.ga,this.ea,this.da,this.R]})};c.prototype.zf=function(){this.ad();this.vb.putImageData(this.fa,0,0);var a=document.createEvent("CustomEvent");a.initCustomEvent("timeupdate",!1,!1,null);this.dispatchEvent(a)};c.prototype.U=null;c.prototype.V=null;c.prototype.bd=null;c.prototype.Yc=
null;c.prototype.Zc=null;c.prototype.createTexture=function(a,d){var b=this.U,c=b.createTexture();b.bindTexture(b.TEXTURE_2D,c);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE);b.uniform1i(b.getUniformLocation(this.V,d),a);return c};c.prototype.compileShader=function(a,d){var b=this.U,c=b.createShader(a);
b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw Error(b.getShaderInfoLog(c));return c};c.prototype.Wd=function(){try{var a=this.U=this.canvas.getContext("webgl")||this.canvas.getContext("experimental-webgl")}catch(b){return!1}if(!a)return!1;var d=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,d);a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,1,1]),a.STATIC_DRAW);this.V=a.createProgram();a.attachShader(this.V,this.compileShader(a.VERTEX_SHADER,T));
a.attachShader(this.V,this.compileShader(a.FRAGMENT_SHADER,ja));a.linkProgram(this.V);if(!a.getProgramParameter(this.V,a.LINK_STATUS))throw Error(a.getProgramInfoLog(this.V));a.useProgram(this.V);this.bd=this.createTexture(0,"YTexture");this.Yc=this.createTexture(1,"CBTexture");this.Zc=this.createTexture(2,"CRTexture");d=a.getAttribLocation(this.V,"vertex");a.enableVertexAttribArray(d);a.vertexAttribPointer(d,2,a.FLOAT,!1,0,0);this.Hb=a.createProgram();a.attachShader(this.Hb,this.compileShader(a.VERTEX_SHADER,
T));a.attachShader(this.Hb,this.compileShader(a.FRAGMENT_SHADER,ka));a.linkProgram(this.Hb);a.useProgram(this.Hb);d=a.getAttribLocation(this.Hb,"vertex");a.enableVertexAttribArray(d);a.vertexAttribPointer(d,2,a.FLOAT,!1,0,0);return!0};c.prototype.ne=function(){var a=this.U,d=new Uint8Array(this.ga.buffer),b=new Uint8Array(this.ea.buffer),c=new Uint8Array(this.da.buffer);a.activeTexture(a.TEXTURE0);a.bindTexture(a.TEXTURE_2D,this.bd);a.texImage2D(a.TEXTURE_2D,0,a.LUMINANCE,this.I,this.G,0,a.LUMINANCE,
a.UNSIGNED_BYTE,d);a.activeTexture(a.TEXTURE1);a.bindTexture(a.TEXTURE_2D,this.Yc);a.texImage2D(a.TEXTURE_2D,0,a.LUMINANCE,this.hb,this.G/2,0,a.LUMINANCE,a.UNSIGNED_BYTE,b);a.activeTexture(a.TEXTURE2);a.bindTexture(a.TEXTURE_2D,this.Zc);a.texImage2D(a.TEXTURE_2D,0,a.LUMINANCE,this.hb,this.G/2,0,a.LUMINANCE,a.UNSIGNED_BYTE,c);a.drawArrays(a.TRIANGLE_STRIP,0,4);a=document.createEvent("CustomEvent");a.initCustomEvent("timeupdate",!1,!1,null);this.dispatchEvent(a)};c.prototype.Tc=0;c.prototype.Xc=!1;
c.prototype.Ve=function(a){this.Xc=!0;this.Z=(a-1)*this.Aa-1;this.la=this.L=this.ka=this.K=0;this.xb=this.yb=this.zb=128;for(this.Tc=this.buffer.c(5);this.buffer.c(1);)this.buffer.advance(8);do this.Se();while(!this.buffer.ge())};c.prototype.Z=0;c.prototype.za=0;c.prototype.ya=0;c.prototype.Ib=0;c.prototype.ib=!1;c.prototype.ce=!1;c.prototype.ka=0;c.prototype.la=0;c.prototype.K=0;c.prototype.L=0;c.prototype.Se=function(){for(var a=0,d=this.aa(Q);34==d;)d=this.aa(Q);for(;35==d;)a+=33,d=this.aa(Q);
a+=d;if(this.Xc)this.Xc=!1,this.Z+=a;else{if(this.Z+a>=this.tf)return;1<a&&(this.xb=this.yb=this.zb=128,this.na==N&&(this.la=this.L=this.ka=this.K=0));for(;1<a;)this.Z++,this.za=this.Z/this.Aa|0,this.ya=this.Z%this.Aa,this.Hd(this.ka,this.la,this.fb,this.cb,this.bb),a--;this.Z++}this.za=this.Z/this.Aa|0;this.ya=this.Z%this.Aa;this.Ib=this.aa(la[this.na]);this.ib=this.Ib&1;this.ce=this.Ib&8;0!=(this.Ib&16)&&(this.Tc=this.buffer.c(5));this.ib?this.la=this.L=this.ka=this.K=0:(this.xb=this.yb=this.zb=
128,this.Te(),this.Hd(this.ka,this.la,this.fb,this.cb,this.bb));for(var a=0!=(this.Ib&2)?this.aa(ma):this.ib?63:0,d=0,b=32;6>d;d++)0!=(a&b)&&this.Re(d),b>>=1};c.prototype.Te=function(){var a,d;this.ce?(a=this.aa(U),0!=a&&1!=this.T?(d=this.buffer.c(this.eb),d=(Math.abs(a)-1<<this.eb)+d+1,0>a&&(d=-d)):d=a,this.K+=d,this.K>(this.T<<4)-1?this.K-=this.T<<5:this.K<-this.T<<4&&(this.K+=this.T<<5),this.ka=this.K,this.Oc&&(this.ka<<=1),a=this.aa(U),0!=a&&1!=this.T?(d=this.buffer.c(this.eb),d=(Math.abs(a)-
1<<this.eb)+d+1,0>a&&(d=-d)):d=a,this.L+=d,this.L>(this.T<<4)-1?this.L-=this.T<<5:this.L<-this.T<<4&&(this.L+=this.T<<5),this.la=this.L,this.Oc&&(this.la<<=1)):this.na==N&&(this.la=this.L=this.ka=this.K=0)};c.prototype.Hd=function(a,d,b,c,e){var g,f,h,l,m,p,n=this.Ec,q=this.Bc,t=this.Cc;g=this.I;f=g-16;h=1==(d&1);l=((this.za<<4)+(d>>1))*g+(this.ya<<4)+(a>>1);m=this.za*g+this.ya<<2;p=m+(g<<2);var r,u,w;if(1==(a&1))if(h)for(;m<p;){r=b[l]+b[l+g];l++;for(h=0;4>h;h++)u=b[l]+b[l+g],l++,w=r+u+2>>2&255,r=
b[l]+b[l+g],l++,w|=r+u+2<<6&65280,u=b[l]+b[l+g],l++,w|=r+u+2<<14&16711680,r=b[l]+b[l+g],l++,w|=r+u+2<<22&4278190080,n[m++]=w;m+=f>>2;l+=f-1}else for(;m<p;){r=b[l++];for(h=0;4>h;h++)u=b[l++],w=r+u+1>>1&255,r=b[l++],w|=r+u+1<<7&65280,u=b[l++],w|=r+u+1<<15&16711680,r=b[l++],w|=r+u+1<<23&4278190080,n[m++]=w;m+=f>>2;l+=f-1}else if(h)for(;m<p;){for(h=0;4>h;h++)w=b[l]+b[l+g]+1>>1&255,l++,w|=b[l]+b[l+g]+1<<7&65280,l++,w|=b[l]+b[l+g]+1<<15&16711680,l++,w|=b[l]+b[l+g]+1<<23&4278190080,l++,n[m++]=w;m+=f>>2;
l+=f}else for(;m<p;){for(h=0;4>h;h++)w=b[l],l++,w|=b[l]<<8,l++,w|=b[l]<<16,l++,w|=b[l]<<24,l++,n[m++]=w;m+=f>>2;l+=f}g=this.hb;f=g-8;h=1==(d/2&1);l=((this.za<<3)+(d/2>>1))*g+(this.ya<<3)+(a/2>>1);m=this.za*g+this.ya<<1;p=m+(g<<1);if(1==(a/2&1))if(h)for(;m<p;){a=c[l]+c[l+g];n=e[l]+e[l+g];l++;for(h=0;2>h;h++)d=c[l]+c[l+g],r=e[l]+e[l+g],l++,b=a+d+2>>2&255,u=n+r+2>>2&255,a=c[l]+c[l+g],n=e[l]+e[l+g],l++,b|=a+d+2<<6&65280,u|=n+r+2<<6&65280,d=c[l]+c[l+g],r=e[l]+e[l+g],l++,b|=a+d+2<<14&16711680,u|=n+r+2<<
14&16711680,a=c[l]+c[l+g],n=e[l]+e[l+g],l++,b|=a+d+2<<22&4278190080,u|=n+r+2<<22&4278190080,t[m]=b,q[m]=u,m++;m+=f>>2;l+=f-1}else for(;m<p;){a=c[l];n=e[l];l++;for(h=0;2>h;h++)d=c[l],r=e[l++],b=a+d+1>>1&255,u=n+r+1>>1&255,a=c[l],n=e[l++],b|=a+d+1<<7&65280,u|=n+r+1<<7&65280,d=c[l],r=e[l++],b|=a+d+1<<15&16711680,u|=n+r+1<<15&16711680,a=c[l],n=e[l++],b|=a+d+1<<23&4278190080,u|=n+r+1<<23&4278190080,t[m]=b,q[m]=u,m++;m+=f>>2;l+=f-1}else if(h)for(;m<p;){for(h=0;2>h;h++)b=c[l]+c[l+g]+1>>1&255,u=e[l]+e[l+
g]+1>>1&255,l++,b|=c[l]+c[l+g]+1<<7&65280,u|=e[l]+e[l+g]+1<<7&65280,l++,b|=c[l]+c[l+g]+1<<15&16711680,u|=e[l]+e[l+g]+1<<15&16711680,l++,b|=c[l]+c[l+g]+1<<23&4278190080,u|=e[l]+e[l+g]+1<<23&4278190080,l++,t[m]=b,q[m]=u,m++;m+=f>>2;l+=f}else for(;m<p;){for(h=0;2>h;h++)b=c[l],u=e[l],l++,b|=c[l]<<8,u|=e[l]<<8,l++,b|=c[l]<<16,u|=e[l]<<16,l++,b|=c[l]<<24,u|=e[l]<<24,l++,t[m]=b,q[m]=u,m++;m+=f>>2;l+=f}};c.prototype.zb;c.prototype.yb;c.prototype.xb;c.prototype.D=null;c.prototype.Re=function(a){var d=0,b;
this.ac(this.D,0);if(this.ib){4>a?(d=this.zb,b=this.aa(na)):(d=4==a?this.yb:this.xb,b=this.aa(oa));if(0<b){var c=this.buffer.c(b);this.D[0]=0!=(c&1<<b-1)?d+c:d+(-1<<b|c+1)}else this.D[0]=d;4>a?this.zb=this.D[0]:4==a?this.yb=this.D[0]:this.xb=this.D[0];this.D[0]<<=8;b=this.Xd;d=1}else b=this.he;for(;;){var e,c=this.aa(pa);if(1==c&&0<d&&0==this.buffer.c(1))break;65535==c?(e=this.buffer.c(6),c=this.buffer.c(8),0==c?c=this.buffer.c(8):128==c?c=this.buffer.c(8)-256:128<c&&(c-=256)):(e=c>>8,c&=255,this.buffer.c(1)&&
(c=-c));d+=e;e=P[d];d++;c<<=1;this.ib||(c+=0>c?-1:1);c=c*this.Tc*b[e]>>4;0==(c&1)&&(c-=0<c?1:-1);2047<c?c=2047:-2048>c&&(c=-2048);this.D[e]=c*qa[e]}1==d?this.ac(this.D,this.D[0]+128>>8):this.ue();4>a?(d=this.ga,c=this.I-8,b=this.za*this.I+this.ya<<4,0!=(a&1)&&(b+=8),0!=(a&2)&&(b+=this.I<<3)):(d=4==a?this.da:this.ea,c=(this.I>>1)-8,b=(this.za*this.I<<2)+(this.ya<<3));this.ib?this.Gd(this.D,d,b,c):this.Cd(this.D,d,b,c)};c.prototype.Gd=function(a,b,c,e){for(var f=0,g=0;8>g;g++){for(var h=0;8>h;h++)b[c++]=
a[f++];c+=e}};c.prototype.Cd=function(a,b,c,e){for(var f=0,g=0;8>g;g++){for(var h=0;8>h;h++)b[c++]+=a[f++];c+=e}};c.prototype.Qe=function(a,b,c,e){for(var f=0,g=0;8>g;g++){for(var h=0;8>h;h++){var m=a[f++];b[c++]=255<m?255:0>m?0:m}c+=e}};c.prototype.Ne=function(a,b,c,e){for(var f=0,g=0;8>g;g++){for(var h=0;8>h;h++){var m=a[f++]+b[c];b[c++]=255<m?255:0>m?0:m}c+=e}};c.prototype.ue=function(){var a,b,c,e,f,g,h,m,l,p,t,n,q=this.D;for(n=0;8>n;++n)a=q[32+n],b=q[16+n]+q[48+n],c=q[40+n]-q[24+n],g=q[8+n]+
q[56+n],h=q[24+n]+q[40+n],e=q[8+n]-q[56+n],f=g+h,m=q[0+n],t=(473*e-196*c+128>>8)-f,g=t-(362*(g-h)+128>>8),h=m-a,l=(362*(q[16+n]-q[48+n])+128>>8)-b,p=m+a,a=h+l,m=p+b,h-=l,b=p-b,c=-g-(473*c+196*e+128>>8),q[0+n]=f+m,q[8+n]=t+a,q[16+n]=h-g,q[24+n]=b-c,q[32+n]=b+c,q[40+n]=g+h,q[48+n]=a-t,q[56+n]=m-f;for(n=0;64>n;n+=8)a=q[4+n],b=q[2+n]+q[6+n],c=q[5+n]-q[3+n],g=q[1+n]+q[7+n],h=q[3+n]+q[5+n],e=q[1+n]-q[7+n],f=g+h,m=q[0+n],t=(473*e-196*c+128>>8)-f,g=t-(362*(g-h)+128>>8),h=m-a,l=(362*(q[2+n]-q[6+n])+128>>8)-
b,p=m+a,a=h+l,m=p+b,h-=l,b=p-b,c=-g-(473*c+196*e+128>>8),q[0+n]=f+m+128>>8,q[1+n]=t+a+128>>8,q[2+n]=h-g+128>>8,q[3+n]=b-c+128>>8,q[4+n]=b+c+128>>8,q[5+n]=g+h+128>>8,q[6+n]=a-t+128>>8,q[7+n]=m-f+128>>8};var L=5,t=0,f=1,V=30,x=1,p=3E5,W=5E7,ha=1,Z=[0,23.976,24,25,29.97,30,50,59.94,60,15,5,10,12,15,0,0],P=new Uint8Array([0,1,8,16,9,2,3,10,17,24,32,25,18,11,4,5,12,19,26,33,40,48,41,34,27,20,13,6,7,14,21,28,35,42,49,56,57,50,43,36,29,22,15,23,30,37,44,51,58,59,52,45,38,31,39,46,53,60,61,54,47,55,62,63]),
aa=new Uint8Array([8,16,19,22,26,27,29,34,16,16,22,24,27,29,34,37,19,22,26,27,29,34,34,38,22,22,26,27,29,34,37,40,22,26,27,29,32,35,40,48,26,27,29,32,35,40,48,58,26,27,29,34,38,46,56,69,27,29,35,38,46,56,69,83]),ba=new Uint8Array([16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16]),qa=new Uint8Array([32,44,42,38,32,25,17,9,44,62,58,52,44,35,24,12,42,58,55,49,
42,33,23,12,38,52,49,44,38,30,20,10,32,44,42,38,32,25,17,9,25,35,33,30,25,20,14,7,17,24,23,20,17,14,9,5,9,12,12,10,9,7,5,2]),Q=new Int16Array([3,6,0,9,12,0,0,0,1,15,18,0,21,24,0,27,30,0,33,36,0,0,0,3,0,0,2,39,42,0,45,48,0,0,0,5,0,0,4,51,54,0,57,60,0,0,0,7,0,0,6,63,66,0,69,72,0,75,78,0,81,84,0,-1,87,0,-1,90,0,93,96,0,99,102,0,105,108,0,111,114,0,0,0,9,0,0,8,117,120,0,123,126,0,129,132,0,135,138,0,0,0,15,0,0,14,0,0,13,0,0,12,0,0,11,0,0,10,141,-1,0,-1,144,0,147,150,0,153,156,0,159,162,0,165,168,0,171,
174,0,177,180,0,183,-1,0,-1,186,0,189,192,0,195,198,0,201,204,0,207,210,0,213,216,0,219,222,0,0,0,21,0,0,20,0,0,19,0,0,18,0,0,17,0,0,16,0,0,35,0,0,34,0,0,33,0,0,32,0,0,31,0,0,30,0,0,29,0,0,28,0,0,27,0,0,26,0,0,25,0,0,24,0,0,23,0,0,22]),ma=new Int16Array([6,3,0,9,18,0,12,15,0,24,33,0,36,39,0,27,21,0,30,42,0,60,57,0,54,48,0,69,51,0,81,75,0,63,84,0,45,66,0,72,78,0,0,0,60,105,120,0,132,144,0,114,108,0,126,141,0,87,93,0,117,96,0,0,0,32,135,138,0,99,123,0,129,102,0,0,0,4,90,111,0,0,0,8,0,0,16,0,0,44,150,
168,0,0,0,28,0,0,52,0,0,62,183,177,0,156,180,0,0,0,1,165,162,0,0,0,61,0,0,56,171,174,0,0,0,2,0,0,40,153,186,0,0,0,48,192,189,0,147,159,0,0,0,20,0,0,12,240,249,0,0,0,63,231,225,0,195,219,0,252,198,0,0,0,24,0,0,36,0,0,3,207,261,0,243,237,0,204,213,0,210,234,0,201,228,0,216,222,0,258,255,0,264,246,0,-1,282,0,285,291,0,0,0,33,0,0,9,318,330,0,306,348,0,0,0,5,0,0,10,279,267,0,0,0,6,0,0,18,0,0,17,0,0,34,339,357,0,309,312,0,270,276,0,327,321,0,351,354,0,303,297,0,294,288,0,300,273,0,342,345,0,315,324,0,336,
333,0,363,375,0,0,0,41,0,0,14,0,0,21,372,366,0,360,369,0,0,0,11,0,0,19,0,0,7,0,0,35,0,0,13,0,0,50,0,0,49,0,0,58,0,0,37,0,0,25,0,0,45,0,0,57,0,0,26,0,0,29,0,0,38,0,0,53,0,0,23,0,0,43,0,0,46,0,0,42,0,0,22,0,0,54,0,0,51,0,0,15,0,0,30,0,0,39,0,0,47,0,0,55,0,0,27,0,0,59,0,0,31]),U=new Int16Array([3,6,0,12,9,0,0,0,0,18,15,0,24,21,0,0,0,-1,0,0,1,27,30,0,36,33,0,0,0,2,0,0,-2,42,45,0,48,39,0,60,54,0,0,0,3,0,0,-3,51,57,0,-1,69,0,81,75,0,78,63,0,72,66,0,96,84,0,87,93,0,-1,99,0,108,105,0,0,0,-4,90,102,0,0,0,
4,0,0,-7,0,0,5,111,123,0,0,0,-5,0,0,7,114,120,0,126,117,0,0,0,-6,0,0,6,153,162,0,150,147,0,135,138,0,156,141,0,129,159,0,132,144,0,0,0,10,0,0,9,0,0,8,0,0,-8,171,198,0,0,0,-9,180,192,0,168,183,0,165,186,0,174,189,0,0,0,-10,177,195,0,0,0,12,0,0,16,0,0,13,0,0,14,0,0,11,0,0,15,0,0,-16,0,0,-12,0,0,-14,0,0,-15,0,0,-11,0,0,-13]),na=new Int8Array([6,3,0,18,15,0,9,12,0,0,0,1,0,0,2,27,24,0,21,30,0,0,0,0,36,33,0,0,0,4,0,0,3,39,42,0,0,0,5,0,0,6,48,45,0,51,-1,0,0,0,7,0,0,8]),oa=new Int8Array([6,3,0,12,9,0,18,
15,0,24,21,0,0,0,2,0,0,1,0,0,0,30,27,0,0,0,3,36,33,0,0,0,4,42,39,0,0,0,5,48,45,0,0,0,6,51,-1,0,0,0,7,0,0,8]),pa=new Int32Array([3,6,0,12,9,0,0,0,1,21,24,0,18,15,0,39,27,0,33,30,0,42,36,0,0,0,257,60,66,0,54,63,0,48,57,0,0,0,513,51,45,0,0,0,2,0,0,3,81,75,0,87,93,0,72,78,0,96,90,0,0,0,1025,69,84,0,0,0,769,0,0,258,0,0,1793,0,0,65535,0,0,1537,111,108,0,0,0,1281,105,102,0,117,114,0,99,126,0,120,123,0,156,150,0,162,159,0,144,147,0,129,135,0,138,132,0,0,0,2049,0,0,4,0,0,514,0,0,2305,153,141,0,165,171,0,180,
168,0,177,174,0,183,186,0,0,0,2561,0,0,3329,0,0,6,0,0,259,0,0,5,0,0,770,0,0,2817,0,0,3073,228,225,0,201,210,0,219,213,0,234,222,0,216,231,0,207,192,0,204,189,0,198,195,0,243,261,0,273,240,0,246,237,0,249,258,0,279,276,0,252,255,0,270,282,0,264,267,0,0,0,515,0,0,260,0,0,7,0,0,1026,0,0,1282,0,0,4097,0,0,3841,0,0,3585,315,321,0,333,342,0,312,291,0,375,357,0,288,294,0,-1,369,0,285,303,0,318,363,0,297,306,0,339,309,0,336,348,0,330,300,0,372,345,0,351,366,0,327,354,0,360,324,0,381,408,0,417,420,0,390,378,
0,435,438,0,384,387,0,0,0,2050,396,402,0,465,462,0,0,0,8,411,399,0,429,432,0,453,414,0,426,423,0,0,0,10,0,0,9,0,0,11,0,0,5377,0,0,1538,0,0,771,0,0,5121,0,0,1794,0,0,4353,0,0,4609,0,0,4865,444,456,0,0,0,1027,459,450,0,0,0,261,393,405,0,0,0,516,447,441,0,516,519,0,486,474,0,510,483,0,504,498,0,471,537,0,507,501,0,522,513,0,534,531,0,468,477,0,492,495,0,549,546,0,525,528,0,0,0,263,0,0,2562,0,0,2306,0,0,5633,0,0,5889,0,0,6401,0,0,6145,0,0,1283,0,0,772,0,0,13,0,0,12,0,0,14,0,0,15,0,0,517,0,0,6657,0,0,
262,540,543,0,480,489,0,588,597,0,0,0,27,609,555,0,606,603,0,0,0,19,0,0,22,591,621,0,0,0,18,573,576,0,564,570,0,0,0,20,552,582,0,0,0,21,558,579,0,0,0,23,612,594,0,0,0,25,0,0,24,600,615,0,0,0,31,0,0,30,0,0,28,0,0,29,0,0,26,0,0,17,0,0,16,567,618,0,561,585,0,654,633,0,0,0,37,645,648,0,0,0,36,630,636,0,0,0,34,639,627,0,663,666,0,657,624,0,651,642,0,669,660,0,0,0,35,0,0,267,0,0,40,0,0,268,0,0,266,0,0,32,0,0,264,0,0,265,0,0,38,0,0,269,0,0,270,0,0,33,0,0,39,0,0,7937,0,0,6913,0,0,7681,0,0,4098,0,0,7425,0,
0,7169,0,0,271,0,0,274,0,0,273,0,0,272,0,0,1539,0,0,2818,0,0,3586,0,0,3330,0,0,3074,0,0,3842]),X=150,ia=1,N=2,ca=3,G=195,M=184,fa=1,ga=175,Y=0,da=181,ea=178,ja="precision mediump float;\nuniform sampler2D YTexture;\nuniform sampler2D CBTexture;\nuniform sampler2D CRTexture;\nvarying vec2 texCoord;\nvoid main() {\nfloat y = texture2D(YTexture, texCoord).r;\nfloat cr = texture2D(CBTexture, texCoord).r - 0.5;\nfloat cb = texture2D(CRTexture, texCoord).r - 0.5;\ngl_FragColor = vec4(\ny + 1.4 * cr,\ny + -0.343 * cb - 0.711 * cr,\ny + 1.765 * cb,\n1.0\n);\n}",
ka="precision mediump float;\nuniform float loaded;\nvarying vec2 texCoord;\nvoid main() {\nfloat c = ceil(loaded-(1.0-texCoord.y));\ngl_FragColor = vec4(c,c,c,1);\n}",T="attribute vec2 vertex;\nvarying vec2 texCoord;\nvoid main() {\ntexCoord = vertex;\ngl_Position = vec4((vertex * 2.0 - 1.0) * vec2(1, -1), 0.0, 1.0);\n}",la=[null,new Int8Array([3,6,0,-1,9,0,0,0,1,0,0,17]),new Int8Array([3,6,0,9,12,0,0,0,10,15,18,0,0,0,2,21,24,0,0,0,8,27,30,0,33,36,0,-1,39,0,0,0,18,0,0,26,0,0,1,0,0,17]),new Int8Array([3,
6,0,9,15,0,12,18,0,24,21,0,0,0,12,27,30,0,0,0,14,39,42,0,36,33,0,0,0,4,0,0,6,54,48,0,45,51,0,0,0,8,0,0,10,-1,57,0,0,0,1,60,63,0,0,0,30,0,0,17,0,0,22,0,0,26])];e.jc=-1;e.pa=-2;e.prototype.kf=function(){this.oa=this.mb=0;this.qd=!1;this.ab=this.o=this.a=this.dc=NaN;this.Ra=null;this.Oa=this.w=NaN;this.j=this.index=0};e.prototype.qb=function(){this.ud(void 0,!0);if(this.Mb){var a;(a=this.pf())&&this.yf(a)}};e.prototype.yf=function(a){for(var b=this.o,c=0;c<a;c++)this.Pb(b),b=b.next;this.o=b;for(a=this.w;a.next&&
a.next.start<=this.o.start;)a=a.next;a.start=this.o.start;a.l=this.o.l;this.w=a};e.prototype.pf=function(){for(var a=0,b=this.o;b&&b.start<this.a.start;)a++,b=b.next;a-=3;return 0<a?a:0};e.prototype.mf=function(a,b,c,e){if(a>this.mb||this.qd)return!1;if(this.ab.end+1==a)var f="";else{for(var g=f=this.o;f&&f.start<a;)g=f,f=f.next;if(g.start<=a&&g.end+1>=a){if(f&&g.end+1==f.start)for(;f&&g.end+1==f.start;)g=f,f=f.next;a=g.end+1}f=f?f.start-1:""}b=(!this.a||e?a:this.a.end+1)+c*b-1;if(a>b)return!1;if(f>
b||""==f)f=b;return{start:a,end:f}};e.prototype.lf=function(){if(!this.Ra){this.Ra={};var a=this;this.Ra.__defineGetter__("length",function(){var b=0;if(a.w){b++;for(var c=a.w;c.next;)c=c.next,b++}return b});this.Ra.start=function(b){for(var c=0,e=a.w;;){if(c==b)return e.l;e=e.next;c++}};this.Ra.end=function(b){for(var c=0,e=a.w;;){if(c==b)return e.m;e=e.next;c++}}}return this.Ra};e.prototype.Dd=function(a){this.mb=this.s?this.mb+a.total:a.total;this.$c=this.mb-4<<3;a.data=new Uint8Array(a.data);
a.next=null;if(this.o)if(this.ab.end+1<=a.start)this.ab.next=a,this.ab=this.ab.next,this.Oa.end+1==a.start?(this.Oa.end=a.end,this.Oa.m=a.m):(a={start:a.start,end:a.end,next:null,l:a.l,m:a.m},this.Oa.next=a,this.Oa=this.Oa.next);else if(this.o.start>=a.end+1)a.next=this.o,this.o=a,this.w.start==a.end+1?(this.w.start=a.start,this.w.l=a.l):(a={start:a.start,end:a.end,next:null,l:a.l,m:a.m},a.next=this.w,this.w=a);else{for(var b=this.o,c=this.o;b.end<a.start;)c=b,b=b.next;a.next=b;c.next=a;for(c=b=this.w;b&&
b.end<a.start;)c=b,b=b.next;c.end+1==a.start&&b.start==a.end+1?(c.end=b.end,c.m=b.m,c.next=b.next):c.end+1==a.start?(c.end=a.end,c.m=a.m):b.start==a.end+1?(b.start=a.start,b.l=a.l):(a={start:a.start,end:a.end,next:null,l:a.l,m:a.m},a.next=c.next,c.next=a)}else this.a=this.ab=this.o=a,this.oa=this.o.data.byteLength,this.Oa=this.w={start:a.start,end:a.end,next:null,l:a.l,m:a.m}};e.prototype.fe=function(){return this.s?!0:this.h?this.a.start!=this.h[this.h.length-1].start||32<=(this.a.data.byteLength<<
3)-this.j:this.index<this.$c};e.prototype.bc=function(){this.j=this.j+7>>3<<3;for(this.index=this.index+7>>3<<3;this.fe();){if(this.ge()){var a=(this.j>>3)+4-this.a.data.byteLength-1;if(0<a){if(this.a.next&&this.a.end+1==this.a.next.start)return this.dc=this.a,this.a=this.a.next,this.oa=this.a.data.byteLength,this.index=this.a.start+a<<3,this.j=a<<3,this.qb(),this.a.data[a];this.ma(this.a.end+1);return e.pa}this.j+=32;this.index+=32;return this.a.data[this.j-8>>3]}this.advance(8)}this.index=this.mb<<
3;return e.jc};e.prototype.ge=function(){if(!this.fe())return!0;var a=this.j+7>>3,b=this.oa-a;if(2<b)return 0==this.a.data[a]&&0==this.a.data[a+1]&&1==this.a.data[a+2];if(this.a.next&&this.a.end+1==this.a.next.start)switch(b){case 2:return 0==this.a.data[a]&&0==this.a.data[a+1]&&1==this.a.next.data[0];case 1:return 0==this.a.data[a]&&0==this.a.next.data[0]&&1==this.a.next.data[1];default:return 0==this.a.next.data[0]&&0==this.a.next.data[1]&&1==this.a.next.data[2]}else return this.ma(this.a.end+1),
e.pa};e.prototype.appendBuffer=function(a,b){var c=new Uint8Array(a.byteLength+b.byteLength);c.set(new Uint8Array(a),0);c.set(new Uint8Array(b),a.byteLength);return c};e.prototype.c=function(a){var b=!1,c=this.j>>3,f=8-this.j%8;if(this.a.data.byteLength<<3>=this.j+a)var h=this.a.data;else if(this.a.next&&this.a.end+1==this.a.next.start)b=!0,h=this.appendBuffer(this.a.data.buffer,this.a.next.data.buffer),this.dc=this.a,this.a=this.a.next,this.oa=this.a.data.byteLength,this.qb();else return this.ma(this.a.end+
1),e.pa;if(f>=a)return this.index+=a,this.j=b?this.index-(this.a.start<<3):this.j+a,h[c]>>f-a&255>>8-a;var g=(this.j+a)%8,m=this.j+a-1>>3,f=h[c]&255>>8-f;for(c++;c<m;c++)f<<=8,f|=h[c];f=0<g?f<<g|h[c]>>8-g:f<<8|h[c];this.index+=a;this.j=b?this.index-(this.a.start<<3):this.j+a;return f};e.prototype.qe=function(a){var b;void 0==b&&(b=1);if(0<a)if(this.a.next&&this.a.end+1==this.a.next.start)this.dc=this.a,this.a=this.a.next,this.oa=this.a.data.byteLength,this.j=a-1,this.index=(this.a.start<<3)+this.j,
b&&this.qb();else return b?(this.ma(this.a.end+1),e.pa):!1;else this.a=this.dc,this.oa=this.a.data.byteLength,this.j=(this.a.data.byteLength<<3)+a,this.index=(this.a.end+1<<3)+a;return!0};e.prototype.advance=function(a){var b;return 0>=(b=this.j+a-((this.oa<<3)-1))?(this.index+=a,this.j+=a):this.qe(b)};e.prototype.oe=function(a){return a<=this.j?(this.index-=a,this.j-=a):this.qe(this.j-a)};e.prototype.seek=function(a){var b=this.o,c=this.a.start;if(this.h){for(var f=0;f<this.h.length;f++)if(this.h[f].end>=
a){if(this.h[f].loaded)var h=a-this.h[f].start;else return this.ma(this.h[f].start),e.pa;break}for(;b.start!=this.h[f].start;)b=b.next;this.a=b;this.oa=this.a.data.byteLength;this.j=h<<3;this.index=a<<3;c!=this.h[f].start&&this.qb();return!0}do{if(b.end>=a&&b.start<=a)return this.a=b,this.oa=this.a.data.byteLength,this.j=a-this.a.start<<3,this.index=a<<3,c!=this.a.start&&this.qb(),!0;if(!b.next||b.next.start>a)return this.ma(a),e.pa;b=b.next}while(1)};b.jsv_helper=function(){};b.jsv_helper.iPhoneVersion=
function(){if(!/(iPhone)/g.test(navigator.userAgent))return NaN;var a=b.screen.height;switch(a){case 480:return"4";case 568:return"5";case 667:return"6";case 736:return"6";default:return 736<a?"6":"4"}};b.jsv_helper.iOsVersion=function(){if(!/(iPhone)/g.test(navigator.userAgent))return NaN;var a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);return parseInt(a[1],10)};if(b.jsv_is_ww){var I=new b.video_jsv;b.addEventListener("message",function(a){var c=a.data;a=c.args&&!Array.isArray(c.args)?
Object.keys(c.args).map(function(a){return c.args[a]}):c.args;switch(c.t){case "event":I.f(c.n,a,!0);break;case "set":I.__lookupSetter__(c.n).apply(I,a);break;case "func":I[c.n].apply(I,a);break;case "eq":I[c.n]=a[0];break;case "jsv_gl":b.jsv_gl[c.n]=a[0]}})}})(window);
